### ISSUE TITLE
没有app前台代码

### ISSUE THREAD

**Issue by yfjl** [macrozheng/mall#1]
没有app前台代码

**Comment by macrozheng** [comment]
看下开发进度，只开发了部分接口，以后会开发。

**Comment by LinXnan** [comment]
> 看下开发进度，只开发了部分接口，以后会开发。
大哥码农有多少年了

**Comment by suethan** [comment]
有没有app的代码+1

**Comment by huangcong0818** [comment]
有没有app的代码+1

**Comment by ShengboZhang** [comment]
web端的界面也没有
请问前端的是否开源,目前进度如何?

**Comment by alloai** [comment]
弄个angular前端 ? 或者react 前端?

**Comment by haoshenpei** [comment]
想请教 用 Elasticsearch ，前端需要 配合后端做些什么工作呢？

**Comment by yigaohui** [comment]
有没有前端app+1

**Comment by suyaoli** [comment]
没有前端代码 不能完整的学习

**Comment by LiuPengGitHubAccount** [comment]
坐等前端App代码，感谢大神分享

**Comment by 260936767** [comment]
坐等。大神好棒

**Comment by guobotry** [comment]
uni-app中有一个开源的电商项目模板，界面很不错，是我目前看到的最好的开源电商APP模板，并且与本项目的app相似度非常高，应该比较容易集成。地址：https://ext.dcloud.net.cn/plugin?id=200
