### ISSUE TITLE
我idea打开项目，总是说缺各种依赖

### ISSUE THREAD

**Issue by GitBiao** [macrozheng/mall#102]
比如这样
![image](https://user-images.githubusercontent.com/28030821/56706784-d6c43580-6748-11e9-8f81-e4d08f0ac843.png)
但是我看pom上边该加的依赖都加了，请问这种情况是怎么回事啊

**Comment by GitBiao** [comment]
![image](https://user-images.githubusercontent.com/28030821/56707203-7cc46f80-674a-11e9-8f93-16fad8c7a0b0.png)
maven这边不下载那些引用

**Comment by GitBiao** [comment]
![image](https://user-images.githubusercontent.com/28030821/56707874-489e7e00-674d-11e9-9dff-c09946d03d73.png)
一个一个install，然后重新打开项目就可以了

**Comment by jerryzhuochuxin** [comment]
maven的重新导入依赖试试
---原始邮件---
发件人:"GitBiao"<notifications@github.com>
发送时间:2019年4月27日 星期六 上午9:13
收件人:"macrozheng/mall"<mall@noreply.github.com>
抄送:"Subscribed"<subscribed@noreply.github.com>
主题:Re: [macrozheng/mall] 我idea打开项目，总是说缺各种依赖 (#102)

Closed#102.

&mdash;
