### ISSUE TITLE
后台这里OmsPromotionServiceImpl->handleNoReduce会崩溃

### ISSUE THREAD

**Issue by Mrfanwei** [macrozheng/mall#103]
当在应用中调用/order/generateConfirmOrder时，后台运行到OmsPromotionServiceImpl->handleNoReduce这个函数的cartPromotionItem.setRealStock(skuStock.getStock()-skuStock.getLockStock());这一行会崩溃掉
希望大佬看下什么问题

**Comment by Mrfanwei** [comment]
因为PmsSkuStock skuStock = getOriginalPrice(promotionProduct,item.getProductSkuId());这里skuStock返回null时会导致崩溃

**Comment by macrozheng** [comment]
可以看下这个：https://github.com/macrozheng/mall/issues/100

**Comment by Mrfanwei** [comment]
谢谢大佬
