### ISSUE TITLE
mysql中这张表pms_sku_stock

### ISSUE THREAD

**Issue by Mrfanwei** [macrozheng/mall#105]
mysql中这张表pms_sku_stock中的信息是什么时候添加的，我在mall-admin-web中添加了一个商品，在pms_sku_stock中没看到增加相应的信息项(pms_product中有了添加的商品信息)

**Comment by macrozheng** [comment]
在添加商品的第三步，填写商品属性中添加的

**Comment by Mrfanwei** [comment]
谢谢
