### ISSUE TITLE
请问权限查询问题，SQL我看先是查询角色权限排除用户权限，然后再union用户权限

### ISSUE THREAD

**Issue by andotorg** [macrozheng/mall#113]
请问权限查询问题，SQL我看先是查询角色权限排除用户权限，然后再union用户权限
您这块是怎么考虑的呢？

**Comment by andotorg** [comment]
UNION 本身就把重复的去掉了

**Comment by macrozheng** [comment]
可以看下我写的教程：https://mp.weixin.qq.com/s/HFAfcSGANrdVJeTmT-7X_A

**Comment by andotorg** [comment]
加权限减权限的问题？

**Comment by jonathonlee** [comment]
权限模块是没有吗
