### ISSUE TITLE
maven报org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing

### ISSUE THREAD

**Issue by tank2737** [macrozheng/mall#114]
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available

**Comment by macrozheng** [comment]
这是你maven依赖没下载下来吧

**Comment by tank2737** [comment]
> 这是你maven依赖没下载下来吧

是的，已经解决了
