### ISSUE TITLE
验证码直接登录

### ISSUE THREAD

**Issue by Mrfanwei** [macrozheng/mall#116]
能不能做成手机验证码直接登录的(省掉注册和输入密码登录的步骤)，现在移动端基本都是这样

**Comment by macrozheng** [comment]
手机验证码需要短信服务，短信服务是收费的，需要你自行实现。

**Comment by Mrfanwei** [comment]
我已经能将getAuthCode获取的验证码发到手机了，但是不知道怎么实现手机验证码注册登录
下面是网建通信用来发送短信的信息：
uid:blueskyfw
key:d41d8cd98f00b204e980

**Comment by Mrfanwei** [comment]
这个是我用的发送短信的工具

[SendMessageUtil.zip](https://github.com/macrozheng/mall/files/3193943/SendMessageUtil.zip)
