### ISSUE TITLE
为什么没有吧admin-web加入这个项目，而是单独提出来呢

### ISSUE THREAD

**Issue by keweiLv** [macrozheng/mall#122]

**Comment by galaxist** [comment]
node项目和java项目揉到一起干嘛？

**Comment by 524300045** [comment]
admin-web是用vue实现的，是前端项目，架构不一样，没办法和JAVA项目融合到一起

**Comment by keweiLv** [comment]
好吧 我本身不是很了解Vue。我学习litemall的时候，他们是一起打包运行的，我也没搞懂怎么融合到一起运行的。

**Comment by IncredibleKenny** [comment]
因为这是一个前后端分离的项目呀
