### ISSUE TITLE
这里图片是如何存储的

### ISSUE THREAD

**Issue by heliusjing** [macrozheng/mall#123]
这里图片是如何存储的

**Comment by 524300045** [comment]
图片使用的是阿里云oss

**Comment by ZainZhao** [comment]
我在添加商品上传图片之后，图片不会显示

**Comment by ZainZhao** [comment]
上传成功了，但是显示不了

**Comment by ZainZhao** [comment]
![20190521134856](https://user-images.githubusercontent.com/28838928/58071431-376f5280-7bcf-11e9-9205-b43b86f3eebd.png)

**Comment by 524300045** [comment]
1.检查下你的OSS服务是不是设置了权限，权限设置为公共读






------------------ 原始邮件 ------------------
发件人: "Zain"<notifications@github.com>; 
发送时间: 2019年5月21日(星期二) 中午1:50
收件人: "macrozheng/mall"<mall@noreply.github.com>; 
抄送: "524300045"<524300045@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [macrozheng/mall] 这里图片是如何存储的 (#123)





 
&mdash;

**Comment by ZainZhao** [comment]
我设置了，浏览器导航栏可以直接访问的，我用url直接写了简单的测试代码也可以

**Comment by ZainZhao** [comment]
![20190521135455](https://user-images.githubusercontent.com/28838928/58071689-0a6f6f80-7bd0-11e9-9069-5de75d950c6b.png)

**Comment by 524300045** [comment]
应该是OSS权限设置的问题，把图片url完整路径给我发下，



------------------ 原始邮件 ------------------
发件人: "Zain"<notifications@github.com>; 
发送时间: 2019年5月21日(星期二) 中午1:56
收件人: "macrozheng/mall"<mall@noreply.github.com>; 
抄送: "524300045"<524300045@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [macrozheng/mall] 这里图片是如何存储的 (#123)





 
&mdash;

**Comment by ZainZhao** [comment]
http://zain-images.oss-cn-beijing.aliyuncs.com/mall/images/20190521/QQ%E6%B5%8F%E8%A7%88%E5%99%A8%E6%88%AA%E5%9B%BE20180915114428.png

**Comment by ZainZhao** [comment]
我叫我同学测试过了，能访问

**Comment by 524300045** [comment]
把这个权限设置下




------------------ 原始邮件 ------------------
发件人: "Zain"<notifications@github.com>; 
发送时间: 2019年5月21日(星期二) 下午2:02
收件人: "macrozheng/mall"<mall@noreply.github.com>; 
抄送: "524300045"<524300045@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [macrozheng/mall] 这里图片是如何存储的 (#123)




我叫我同学测试过了，能访问
 
&mdash;

**Comment by ZainZhao** [comment]
哪个？朋友

**Comment by ZainZhao** [comment]
问题解决了，在index.html下加上<meta name="referrer" content="no-referrer" />就好了

**Comment by ZainZhao** [comment]
`<meta name="referrer" content="no-referrer" />`
