### ISSUE TITLE
mall maven package问题

### ISSUE THREAD

**Issue by Mrfanwei** [macrozheng/mall#125]
我在idea的maven projects中直接点击mall目录下的package,会出现下面的异常：

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.macro.mall:mall-portal:1.0-SNAPSHOT: Could not find artifact com.macro.mall:mall:pom:1.0-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 21, column 13

**Comment by apert4160** [comment]
怎么解决的请问？
