### ISSUE TITLE
Whitelabel Error Page, This application has no explicit mapping for /error

### ISSUE THREAD

**Issue by le773** [macrozheng/mall#127]
本地安装mysql，创建root账号密码，并代码clone到本地，idea编译后，启动mall-admin main方法报错如下：
`Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sun May 26 16:37:00 CST 2019
There was an unexpected error (type=Not Found, status=404).
No message available`
参考 [解决This application has no explicit mapping for /error, so you are seeing this 错误](https://zhuanlan.zhihu.com/p/34496461)后仍然报错，博主能帮忙分析下什么原因吗？

**Comment by dguanggg** [comment]
兄弟，我的import无法识别，能指教一下吗？

**Comment by le773** [comment]
> 兄弟，我的import无法识别，能指教一下吗？
> ![image](https://user-images.githubusercontent.com/43173424/58380436-9bd14e00-7fe3-11e9-831d-b51b0123592c.png)

你new一个spring工程看能不能运行

**Comment by macrozheng** [comment]
你应该访问这个地址：http://localhost:8080/swagger-ui.html，不应该直接访问http://localhost:8080

**Comment by le773** [comment]
> 你应该访问这个地址：[http://localhost:8080/swagger-ui.html，不应该直接访问http://localhost:8080](http://localhost:8080/swagger-ui.html%EF%BC%8C%E4%B8%8D%E5%BA%94%E8%AF%A5%E7%9B%B4%E6%8E%A5%E8%AE%BF%E9%97%AEhttp://localhost:8080)

3q!  刚刚才明白这个项目怎么debug

**Comment by dguanggg** [comment]
> > 兄弟，我的import无法识别，能指教一下吗？
> > ![image](https://user-images.githubusercontent.com/43173424/58380436-9bd14e00-7fe3-11e9-831d-b51b0123592c.png)
> 
> 你new一个spring工程看能不能运行

你们就把项目下载下来，然后Import进去就可以使用了？我本地配置应该都没有问题的，我其它项目都可以正常使用。
