### ISSUE TITLE
运行不了，无法导入包？？！

### ISSUE THREAD

**Issue by dguanggg** [macrozheng/mall#128]
本地maven路径没问题，就是Import无法识别

**Comment by dguanggg** [comment]
![image](https://user-images.githubusercontent.com/43173424/58380369-de465b00-7fe2-11e9-800f-8330c589955e.png)

**Comment by zhyank** [comment]
[`你需要配置一下idea的Maven，最好使用本地安装的maven,然后设置镜像源。参考这篇文章```](https://juejin.im/post/5a4a5e2bf265da4322418d7f)
