### ISSUE TITLE
请问mall-app-web 前端的源码什么时候开源呢？有计划开源吗？

### ISSUE THREAD

**Issue by mack007liu** [macrozheng/mall#130]
请问mall-app-web 前端的源码什么时候开源呢？有计划开源吗？

**Comment by macrozheng** [comment]
暂时还未开发，目前还在完善教程。

**Comment by qiaokun-sh** [comment]
强烈希望开源前端

**Comment by Rainyn** [comment]
前端什么时候开源呢？参与您的开发也可以啊

**Comment by leegtang** [comment]
可以先开发mall-app-web，保持完整性。然后再完善教程。

**Comment by johnchunge** [comment]
强烈希望开源前端

**Comment by yushengling** [comment]
你太强大了 ,我是搞前端的,

**Comment by anyetanxi2017** [comment]
> 暂时还未开发，目前还在完善教程。

目前只有后端教程.前端的没有是吗?

**Comment by qinzhen2607517** [comment]
请问什么时候开源mall-app-web

**Comment by WANDERERLikeMe** [comment]
同求mall-app-web

**Comment by softsrc** [comment]
@macrozheng 代码文档以及代码风格相当给力，想必为码友们操碎了心，精力无暇顾及app这块，是不是可以先把仓库捡起来，给码友们树个框子，然后大家协力做这个事情呢

**Comment by Arthur-Song** [comment]
作者文档很不错，我按照已有的api还有补全修改了部分，使用flutter开发完成了30%的app

**Comment by AdminTestsGitHub** [comment]
移动开发者，可协助开发App，有需要请联系我。

**Comment by xuwanhai** [comment]
大神，请问mall-app-web 前端这部分开发有计划了吗？

**Comment by maxiaoxiong123** [comment]
@https://github.com/xuwanhai对不起还没有

**Comment by jetablezhu** [comment]
大伙对前端的需求最旺啊:heart_eyes:

**Comment by iceslove** [comment]
想基于你的后端开发一版微信小程序版

**Comment by zhyank** [comment]
建议先把前端的项目架构搭建起来，大家添砖加瓦，会更快

**Comment by 15093136163** [comment]
希望能跟着大神好好提升一下  刚学完进了个公司没任务 第一年 我囧啊

**Comment by oliverldx** [comment]
> 作者文档很不错，我按照已有的api还有补全修改了部分，使用flutter开发完成了30%的app

可以开源出来么？

**Comment by liangxuanjia** [comment]
强烈建议开源前端，star、star、star

**Comment by chongchongzi** [comment]
强烈建议开源前端，star、star、star

**Comment by KandyYe** [comment]
希望大佬先把前端的项目架构搭建起来，大家可以一起来完善。

**Comment by wpzero** [comment]
作为java的入门人员，感觉作者的代码和教程非常有帮助。我感觉你可以开始搭建，可以不完善，但是至少整个项目是完整的。

**Comment by IamAScholar** [comment]
希望大佬开源出来

**Comment by 54dujianchao** [comment]
> @macrozheng 代码文档以及代码风格相当给力，想必为码友们操碎了心，精力无暇顾及app这块，是不是可以先把仓库捡起来，给码友们树个框子，然后大家协力做这个事情呢

确实写的太好了 ，感觉按照教程 ，学的很快。。。iOSer转Javaer中

**Comment by JsBlueCat** [comment]
写的特别好，大佬什么时候开源前端项目

**Comment by staryjp** [comment]
期待 app,不然总感觉不完整

**Comment by TProgram** [comment]
我们团队近期在做电商相关小程序，采用的 macro 大佬的后台，最近也把**前端小程序**的代码**开源**出来了，希望可以帮助到大家。
https://github.com/TProgram/mall-app-web

基本上无缝兼容该后台，有一些微信相关的接口有做补充，近期后整理增加到 https://github.com/TProgram/mall 中，欢迎大家一起讨论学习

**Comment by TProgram** [comment]
> 期待 app,不然总感觉不完整

我们团队近期在做电商相关小程序，采用的 macro 大佬的后台，最近也把前端小程序的代码开源出来了，希望可以帮助到大家。
https://github.com/TProgram/mall-app-web

基本上无缝兼容该后台，有一些微信相关的接口有做补充，近期后整理增加到 https://github.com/TProgram/mall 中，欢迎大家一起讨论学习

**Comment by zhouzongbo** [comment]
1


| |
flink
|
|
zhoubo844@163.com
|
签名由网易邮箱大师定制
在2020年8月17日 22:48，TProgram<notifications@github.com> 写道：

期待 app,不然总感觉不完整

我们团队近期在做电商相关小程序，采用的 macro 大佬的后台，最近也把前端小程序的代码开源出来了，希望可以帮助到大家。
https://github.com/TProgram/mall-app-web

基本上无缝兼容该后台，有一些微信相关的接口有做补充，近期后整理增加到 https://github.com/TProgram/mall 中，欢迎大家一起讨论学习

**Comment by wljgithub** [comment]
仰慕一下大佬，真的硬核。

**Comment by NicholasHwang** [comment]
期待

**Comment by aaa7636602** [comment]
app代码？用什么写的？原生安卓和ios吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nicholas Huang"<notifications@github.com&gt;; 
发送时间: 2021年2月4日(星期四) 上午10:21
收件人: "macrozheng/mall"<mall@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [macrozheng/mall] 请问mall-app-web 前端的源码什么时候开源呢？有计划开源吗？ (#130)





 
期待

**Comment by aaa7636602** [comment]
> 作者文档很不错，我按照已有的api还有补全修改了部分，使用flutter开发完成了30%的app

分享出来看哈

**Comment by ysun** [comment]
您好。PC端的前台 前端代码，有计划开源吗？

**Comment by erduoJiang** [comment]
大佬，啥时候有移动端的啊

**Comment by ora19982022** [comment]
看预览好像已经做出来了，什么时候开源啊？
