### ISSUE TITLE
看了作者项目,受到启发很大，目前有一个关于查询问题想咨询一下。

### ISSUE THREAD

**Issue by liezu** [macrozheng/mall#132]
假如有两个表
A表 id name
B表 id name A.id

如果筛选条件中有一个是需要通过A表的name来查询B表的数据，这种项目中有例子吗？如果没有，一般如何实现？
我目前能想到的一个办法是通过A表中name字段的模糊查询,拿到查询结果的id集合，再在B表中用where in a.id（）的方式来进行查询，但是感觉这样好low，作者有没有其它好的方法？

**Comment by macrozheng** [comment]
left jion 两张表，以A的name模糊查询即可。

**Comment by liezu** [comment]
好的，多谢！
