### ISSUE TITLE
app方案

### ISSUE THREAD

**Issue by virtuecai** [macrozheng/mall#133]
您好， 请问app款有考虑使用什么方案吗？
据我目前了解的 uni-app比较火，学习成本比较低， 上手比较快。
一套发布多平台。

**Comment by macrozheng** [comment]
可以采用flutter

**Comment by virtuecai** [comment]
希望不不要才有flutter，希望不不要才有flutter，希望不不要才有flutter

**Comment by awfeequdng** [comment]
最近在学习flutter，如果可以的话，我愿与朋友们一起开发前端部分

**Comment by guobotry** [comment]
uni-app中有一个开源的电商项目模板，界面很不错，是我目前看到的最好的开源电商APP模板，并且与本项目的app相似度非常高，应该比较容易集成。地址：https://ext.dcloud.net.cn/plugin?id=200

**Comment by virtuecai** [comment]
> uni-app中有一个开源的电商项目模板，界面很不错，是我目前看到的最好的开源电商APP模板，并且与本项目的app相似度非常高，应该比较容易集成。地址：https://ext.dcloud.net.cn/plugin?id=200

+1

**Comment by virtuecai** [comment]
> > uni-app中有一个开源的电商项目模板，界面很不错，是我目前看到的最好的开源电商APP模板，并且与本项目的app相似度非常高，应该比较容易集成。地址：https://ext.dcloud.net.cn/plugin?id=200
> 
> +1

可否加个微信或者qq
