### ISSUE TITLE
UmsMemberCouponServiceImpl 中关于优惠券领取后减扣问题

### ISSUE THREAD

**Issue by liuhaolian** [macrozheng/mall#134]
//判断用户领取的优惠券数量是否超过限制
        SmsCouponHistoryExample couponHistoryExample = new SmsCouponHistoryExample();
        couponHistoryExample.createCriteria().andCouponIdEqualTo(couponId).andMemberIdEqualTo(currentMember.getId());
        int count = couponHistoryMapper.countByExample(couponHistoryExample);
        if(count>=coupon.getPerLimit()){
            return new CommonResult().failed("您已经领取过该优惠券");
        }
        //生成领取优惠券历史
        SmsCouponHistory couponHistory = new SmsCouponHistory();
        couponHistory.setCouponId(couponId);
        couponHistory.setCouponCode(generateCouponCode(currentMember.getId()));
        couponHistory.setCreateTime(now);
        couponHistory.setMemberId(currentMember.getId());
        couponHistory.setMemberNickname(currentMember.getNickname());
        //主动领取
        couponHistory.setGetType(1);
        //未使用
        couponHistory.setUseStatus(0);
        couponHistoryMapper.insert(couponHistory);
        //修改优惠券表的数量、领取数量
        coupon.setCount(coupon.getCount()-1);
        coupon.setReceiveCount(coupon.getReceiveCount()==null?1:coupon.getReceiveCount()+1);
        couponMapper.updateByPrimaryKey(coupon);

在一开始查询出 优惠券信息，最后在进行减扣，在多线程环境下，会不会出现，最终数量变为负数的情况？类似于秒杀，超卖了，一开始进来查询，对于查询，mysql 没有锁机制，如果两个线程同时访问，取到相同的优惠券信息，然后都去更新，会不会导致最终的数量不一致？请问会不会有这种情况出现，求指教！

**Comment by macrozheng** [comment]
我上面已经判断了：
`        if(coupon.getCount()<=0){
            return CommonResult.failed("优惠券已经领完了");
        }`
而且这个领取优惠券方法上面开启了事务，只要代码运行到判断优惠券的的那段代码时，那张优惠券的记录就会被数据库行锁锁住，除非这个事务结束，否则其他事务无法更改。

**Comment by liuhaolian** [comment]
对于select 查询没有锁机制，事务是不会加锁，在判断if(coupon.getCount()<=0){ return CommonResult.failed("优惠券已经领完了"); }之前，假如只剩最后一张券，多个人并发，同时拿到了这一张券，然后数量都是1，接着都像下进行操作，那么就会券领的数量大于原来有的数量。不知道，有没有这种情况出现，菜鸟一枚，来学习！

**Comment by isely** [comment]
是的，这个没有处理并发大的时候，在这个里面没有加锁应该对有数量限制的优惠券进行加锁操作，并且可以排队等待。同时不能放在一个事务中执行，否则，同一事务中，数据有缓存，会导致在并发大的情况下数据成负数的情况。与账户的余额一个道理。
