### ISSUE TITLE
请问下 EsProductRepository.findByNameOrSubTitleOrKeywords() 具体实现逻辑是怎样

### ISSUE THREAD

**Issue by chennldev** [macrozheng/mall#135]
您好，最近在研究您的这个项目，关于mall-search工程中的 EsProductRepository 的 findByNameOrSubTitleOrKeywords 方法没有相关实现，请问是如何查询出来结果的，望解答，谢谢

**Comment by macrozheng** [comment]
你可以看下这个：https://mp.weixin.qq.com/s/op7CTQS5dGOKv5BvRbeFow

**Comment by chennldev** [comment]
> 你可以看下这个：https://mp.weixin.qq.com/s/op7CTQS5dGOKv5BvRbeFow

感谢解答，受教了
