### ISSUE TITLE
并发锁定库存问题

### ISSUE THREAD

**Issue by cleverdb** [macrozheng/mall#136]
` private void lockStock(List<CartPromotionItem> cartPromotionItemList) {
        for (CartPromotionItem cartPromotionItem : cartPromotionItemList) {
            PmsSkuStock skuStock = skuStockMapper.selectByPrimaryKey(cartPromotionItem.getProductSkuId());
            skuStock.setLockStock(skuStock.getLockStock() + cartPromotionItem.getQuantity());
            skuStockMapper.updateByPrimaryKeySelective(skuStock);
        }
    }`
大佬，我感觉并发情况下锁定库存会有问题，您觉得呢？

**Comment by isely** [comment]
嗯应该是会有问题，没有排队，没有等待。没有真正锁定。

**Comment by Mrgrtt** [comment]
这个是不是该用消息队列或分布式锁呢？

**Comment by kongchong** [comment]
希望大佬能对这边业务进行完善

**Comment by wangjia2016** [comment]
这里肯定会超卖的，没有 并发控制
