### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by gaochenfeng** [macrozheng/mall#138]
**http://localhost:8080/**
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Jun 11 16:52:11 CST 2019
There was an unexpected error (type=Not Found, status=404).
No message available

**http://localhost:8080/admin/login**

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Jun 11 16:52:39 CST 2019
There was an unexpected error (type=Bad Request, status=400).
Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "login"

**Comment by dcfwow** [comment]
http://localhost:8080/swagger-ui.html

**Comment by macrozheng** [comment]
你可以看下这个：https://github.com/macrozheng/mall/issues/127
