### ISSUE TITLE
关于毕业设计的授权

### ISSUE THREAD

**Issue by ivy-lee-zhou** [macrozheng/mall#139]
您好，我计划用您的项目做毕业设计，论文的方向是测试。我想我需要拿到您的授权？请您看到后回复我，谢谢您！

**Comment by guangLee** [comment]
哥们，这个项目不是我原创的，我fork别人的，你问问原作者吧。如果是我，直接拿来用， 不用问，哈哈

在 2019-06-12 09:35:41，"ivy-lee-zhou" <notifications@github.com> 写道：


您好，我计划用您的项目做毕业设计，论文的方向是测试。我想我需要拿到您的授权？请您看到后回复我，谢谢您！

**Comment by guangLee** [comment]
回复错了，不好意思。我以为是单独发给我的，抱歉，抱歉！

在 2019-06-12 09:47:46，"光咣" <lihg66@163.com> 写道：
哥们，这个项目不是我原创的，我fork别人的，你问问原作者吧。如果是我，直接拿来用， 不用问，哈哈

在 2019-06-12 09:35:41，"ivy-lee-zhou" <notifications@github.com> 写道：


您好，我计划用您的项目做毕业设计，论文的方向是测试。我想我需要拿到您的授权？请您看到后回复我，谢谢您！

**Comment by macrozheng** [comment]
自行遵照本项目开源协议即可。
