### ISSUE TITLE
这项目删除都不用判断该数据是否是该用户下的吗？ 直接传个id就能删除了？

### ISSUE THREAD

**Issue by hackeryutu** [macrozheng/mall#143]
@ApiOperation("删除浏览记录")
    @RequestMapping(value = "/delete", method = RequestMethod.POST)
    @ResponseBody
    public CommonResult delete(@RequestParam("ids") List<String> ids) {
        int count = memberReadHistoryService.delete(ids);
        if (count > 0) {
            return CommonResult.success(count);
        } else {
            return CommonResult.failed();
        }
    }

**Comment by macrozheng** [comment]
前台商城接口暂时不完善。
