### ISSUE TITLE
Sku属性设计。。。。

### ISSUE THREAD

**Issue by berlinsaint** [macrozheng/mall#147]
说实话sku这块前台代码以及后台存储总感觉有点恶心；我给改成了一个json字段存储了。。。前台代码那儿感觉代码太。。。。。。。

**Comment by berlinsaint** [comment]
有没有考虑过重写这块。。。前台 添加 销售属性和 参数属性的时候。。

**Comment by macrozheng** [comment]
我也觉得有点别扭，目前销售属性只能支持三个，后期会考虑重新设计。

**Comment by yrong** [comment]
数据结构有点散,销售属性感觉应该引用另一个字典表,3个扩展字段太怪了，json存储更合理

**Comment by king02071224** [comment]
> 数据结构有点散,销售属性感觉应该引用另一个字典表,3个扩展字段太怪了，json存储更合理.发个链接供参考:
> https://augustrush.me/post/database-design-and-comprehension.html

这个网址怎么访问不了了

**Comment by yrong** [comment]
> > 数据结构有点散,销售属性感觉应该引用另一个字典表,3个扩展字段太怪了，json存储更合理.发个链接供参考:
> > https://augustrush.me/post/database-design-and-comprehension.html
> 
> 这个网址怎么访问不了了

https://app.yinxiang.com/shard/s71/nl/14571354/d0621640-14e7-4160-83f9-3bfa5deacb65?title=%E4%BB%8E%E5%95%86%E5%93%81SPU%E5%92%8CSKU%E8%A1%A8%E7%9C%8B%E6%95%B0%E6%8D%AE%E5%BA%93%E8%A1%A8%E7%BB%93%E6%9E%84%E8%AE%BE%E8%AE%A1%20-%20AugustRush

**Comment by jetablezhu** [comment]
> 数据结构有点散,销售属性感觉应该引用另一个字典表,3个扩展字段太怪了，json存储更合理.发个链接供参考:
> https://augustrush.me/post/database-design-and-comprehension.html

危险网站，打不开

**Comment by wangjia2016** [comment]
规格项
规格值
规格
三张表 然后采用json结合的方式就够了

**Comment by AnOldFather** [comment]
对的json可以的

**Comment by macrozheng** [comment]
已经优化过了，具体查看[《商品SKU功能设计与优化》](http://www.macrozheng.com/#/technology/product_sku)
