### ISSUE TITLE
减少代码量

### ISSUE THREAD

**Issue by varyuan** [macrozheng/mall#149]
@Controller,@ResponseBody 换成@RestController
@RequestMapping(value = "/listAll", method = RequestMethod.GET) 换成@GetMapping 

你觉得怎么样,会不会在某些情况下有问题

**Comment by macrozheng** [comment]
都可以的，只是改成@RestController以后，SwaggerUI中生成文档的请求参数如果不添加@RequestParam注解都会变成@RequestBody形式。

**Comment by huwangw** [comment]
> @controller,@responsebody 换成@RestController
> @RequestMapping(value = "/listAll", method = RequestMethod.GET) 换成@GetMapping
> 
> 你觉得怎么样,会不会在某些情况下有问题



> @controller,@responsebody 换成@RestController
> @RequestMapping(value = "/listAll", method = RequestMethod.GET) 换成@GetMapping
> 
> 你觉得怎么样,会不会在某些情况下有问题



> @controller,@responsebody 换成@RestController
> @RequestMapping(value = "/listAll", method = RequestMethod.GET) 换成@GetMapping
> 
> 你觉得怎么样,会不会在某些情况下有问题

是不是伟弟？？
