### ISSUE TITLE
filter登录认证问题,用于实现验证码注册登录

### ISSUE THREAD

**Issue by Mrfanwei** [macrozheng/mall#150]
Hi,你好：
我在portal->SecurityConfig.java->configure中加入 
.antMatchers(HttpMethod.POST,
                        "/sso/authentication/mobile/*"，
                         "/sso/authentication/mobile/**/*"
                )
                .permitAll()

访问后台：http://localhost:8085/sso/authentication/mobile?username=fanwei&password=1231223hai

为什么在UsernamePasswordAuthenticationFilter->doFilter中执行requiresAuthentication时返回为false,不是应该返回true吗，如果要返回为true应该怎么配置

**Comment by Mrfanwei** [comment]
下面是整个configure代码：
protected void configure(HttpSecurity http) throws Exception {
        http.apply(validateCodeSecurityConfig)
                .and()
                .apply(smsCodeAuthenticationSecurityConfig)
                .and().
                authorizeRequests()
                .antMatchers(HttpMethod.GET, // 允许对于网站静态资源的无授权访问
                        "/",
                        "/*.html",
                        "/favicon.ico",
                        "/**/*.html",
                        "/**/*.css",
                        "/**/*.js",
                        "/swagger-resources/**",
                        "/v2/api-docs/**"
                )
                .permitAll()
                .antMatchers(HttpMethod.POST,
                        "/sso/authentication/mobile/**/*",
                        "/sso/authentication/mobile/*"
                )
                .permitAll()
                .antMatchers(HttpMethod.OPTIONS)//跨域请求会先进行一次options请求
                .permitAll()
                .antMatchers(
                        "/sso/*",//登录注册
                        "/home/**"//首页接口
                )
                .permitAll()
                .antMatchers("/member/**","/returnApply/**")// 测试时开启
                .permitAll()
                .anyRequest()// 除上面外的所有请求全部需要鉴权认证
                .authenticated()
                .and()
                .exceptionHandling()
                .accessDeniedHandler(new GoAccessDeniedHandler())
                .authenticationEntryPoint(new GoAuthenticationEntryPoint())
                .and()
                .formLogin()
                .loginPage("/sso/authentication/mobile")
                .successHandler(new GoAuthenticationSuccessHandler())
                .failureHandler(new GoAuthenticationFailureHandler())
                .and()
                .logout()
                .logoutUrl("/sso/logout")
                .logoutSuccessHandler(new GoLogoutSuccessHandler())
                .invalidateHttpSession(true)
                .deleteCookies("JSESSIONID")
                .and()
                .csrf()
                .disable();//开启basic认证登录后可以调用需要认证的接口
    }

**Comment by macrozheng** [comment]
portal如果要自定义登录接口的话，需要自己实现登录验证逻辑，可以参考下这个：[mall整合SpringSecurity和JWT实现认证和授权（一）](https://juejin.im/post/5cf90fa5e51d455d6d5357d3)和[mall整合SpringSecurity和JWT实现认证和授权（二）](https://juejin.im/post/5cfa0933f265da1b8f1ab2da)

**Comment by Mrfanwei** [comment]
好的，谢谢
