### ISSUE TITLE
The POM for com.macro.mall:mall-mbg:jar:1.0-SNAPSHOT is missing, no dependency information available

### ISSUE THREAD

**Issue by guanhai562** [macrozheng/mall#151]
在使用Docker部署 SpringBoot 应用部署的时候,构建的时候报了如下错误.
我使用的是IDEA,我的dockerHost地址设置的是Xshell连接的地址http://192.168.1.143:22.不知道是不是呢?
请问如何解决,先谢谢了!
[INFO] Building mall-admin 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.macro.mall:mall-mbg:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.231 s
[INFO] Finished at: 2019-06-25T20:02:31+08:00
[INFO] Final Memory: 24M/331M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mall-admin: Could not resolve dependencies for project com.macro.mall:mall-admin:jar:1.0-SNAPSHOT: Could not find artifact com.macro.mall:mall-mbg:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Process finished with exit code 1

**Comment by macrozheng** [comment]
你可以看下这篇文章：[使用Maven插件构建Docker镜像](https://mp.weixin.qq.com/s/q2KDzHbPkf3Q0EY8qYjYgw)

**Comment by macrozheng** [comment]
Could not find artifact com.macro.mall:mall-mbg:jar:1.0-SNAPSHOT，这个找不到需要把mall-mbg使用maven install安装到本地maven仓库

**Comment by guanhai562** [comment]
谢谢,已解决.主要还是不熟悉docker.我再熟悉下^_^
参考了
https://mp.weixin.qq.com/s/q2KDzHbPkf3Q0EY8qYjYgw
https://mp.weixin.qq.com/s/0fVMK107i5bBq8kGQqg8KA
https://mp.weixin.qq.com/s/d_CuljDTJq680NTndAay8g
