### ISSUE TITLE
关于权限！

### ISSUE THREAD

**Issue by wuzhihang0** [macrozheng/mall#153]
大佬，啥时候上权限啊！

**Comment by macrozheng** [comment]
接口已有，只是页面没有实现

**Comment by xikaka** [comment]
、权限管理、设置等模块，其实就想看你的这个模快呢

**Comment by MrEric125** [comment]
感觉大佬目前后台获取用户信息是由很大的性能问题的，请求每个地址都会调用SecurityConfig 的userDetailService()，每次都会查数据库，

**Comment by virtuecai** [comment]
大佬， 请问什么时候出权限这块，很期待！

**Comment by johnchunge** [comment]
同期待

**Comment by jetablezhu** [comment]
> 感觉大佬目前后台获取用户信息是由很大的性能问题的，请求每个地址都会调用SecurityConfig 的userDetailService()，每次都会查数据库，

大家一起使劲，才能做到最好啊，找到问题，就改起来

**Comment by zyfsuzy** [comment]
权限管理的页面什么时候有

**Comment by chengqwerty** [comment]
请问后台现在是不是还没有权限啊？用户现在登录了，所有的接口就都可以调用吗？

**Comment by ChinoJ1** [comment]
有权限，但是显示错误500
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"chengcheng"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年12月2日(星期一) 下午5:24
 收件人:&nbsp;"macrozheng/mall"<mall@noreply.github.com&gt;;
 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
 主题:&nbsp;Re: [macrozheng/mall] 关于权限！ (#153)

 

 
请问后台现在是不是还没有权限啊？用户现在登录了，所有的接口就都可以调用吗？

**Comment by chengqwerty** [comment]
> 有权限，但是显示错误500
> …

没看到后台判断权限的代码?我想看用户每次请求，后台判断用户是否有这个接口权限的代码？我之前自己有写过spring security在方法上加注解判断，但是这里没找到实现类似逻辑的代码。

**Comment by macrozheng** [comment]
权限功能已经添加
