### ISSUE TITLE
请教关于商品信息更新的几个问题

### ISSUE THREAD

**Issue by aboutZZ** [macrozheng/mall#154]
1. 当添加、删除或更新商品后，商品信息如何同步至Elasticsearch？（未见有同步至ES的代码）

2. 当更新商品后，已添加至购物车中的商品（特别是商品规格）如何处理？更新商品的代码中，无论是否更新了SKU，都是先删除SKU表数据，然后重新插入，这导致 SKU 的id变化，购物车中的商品也将全部失效

**Comment by macrozheng** [comment]
可以使用消息队列将商品信息同步到ES，你可以使用oms_cart_item表中的product_sku_code来查找sku，这个字段相当于是商品的条码，商品条码一样就是同一个商品。

**Comment by aboutZZ** [comment]
感谢解答
