### ISSUE TITLE
关于延时队列的一个疑问

### ISSUE THREAD

**Issue by kingtiger2** [macrozheng/mall#159]
订单设置 这里的超时时间,假如现在是60分钟,队列里面有一条数据a,然后改成10分钟了,里面新来一条数据b,这个b是要等a过60分钟消费完,还是就只等10分钟????

**Comment by macrozheng** [comment]
只等10分钟

**Comment by kingtiger2** [comment]
你确认吗? 为什么要关闭帖子啊,这明显就不对,太不负责了!!!!

**Comment by cws1981** [comment]
rabbitmq 的延时队列 是要等前一个出去才会执行下一个
