### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by zhonghuasheng** [macrozheng/mall#16]
@macrozheng 最近提交的代码有Encoding的问题
![screenshot 5](https://user-images.githubusercontent.com/16185320/50416965-5525cf00-085e-11e9-8756-bb149564ffc4.png)
![iso-8859-1](https://user-images.githubusercontent.com/16185320/50416971-5eaf3700-085e-11e9-9504-94f40354b2d0.PNG)

**Comment by guoxiaoxu** [comment]
这不是问题，idea中自己在file encoding 中设置转换为本地ascll.eclipse需要插件支持？
