### ISSUE TITLE
mysql connect error

### ISSUE THREAD

**Issue by maxiao1204** [macrozheng/mall#160]
When I start the modules, there is an error occurred: 
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)

but I have configed the user and password of mysql database in generator.properties:
jdbc.userId=root
jdbc.password=123456 

is there any other config?

**Comment by macrozheng** [comment]
你看下数据库密码是root:https://github.com/macrozheng/mall/blob/master/mall-admin/src/main/resources/application-dev.yml

**Comment by bbbdbbb** [comment]
你好，这邮件你是发错人了嘛？




------------------ 原始邮件 ------------------
发件人: "macro"<notifications@github.com>;
发送时间: 2019年7月3日(星期三) 晚上8:24
收件人: "macrozheng/mall"<mall@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [macrozheng/mall] mysql connect error (#160)




你看下数据库密码是root:https://github.com/macrozheng/mall/blob/master/mall-admin/src/main/resources/application-dev.yml

**Comment by maxiao1204** [comment]
> 你看下数据库密码是root:https://github.com/macrozheng/mall/blob/master/mall-admin/src/main/resources/application-dev.yml

thank you，that's the failure reason!
