### ISSUE TITLE
mall-admin和mall-admin-web布署到云服务器上之后有跨域问题

### ISSUE THREAD

**Issue by mattzhang27** [macrozheng/mall#168]
mall-admin和mall-admin-web布署到云服务器上之后有跨域问题

**Comment by macrozheng** [comment]
安装这两个教程来应该是没有跨域问题的，[mall在Linux环境下的部署（基于Docker容器）](https://mp.weixin.qq.com/s/0fVMK107i5bBq8kGQqg8KA)，[mall前端项目的安装与部署](https://mp.weixin.qq.com/s/_hlSxjpfOOetTpw0mL-Pxg)

**Comment by mattzhang27** [comment]
mall-admin我没有用docker安装，直接运行在linux的tomcat 上的，mall-admin-web是打包后运行在同一台机器的nginx上，不知道怎么会出现cors被禁的问题
