### ISSUE TITLE
关于延时队列的一个疑问

### ISSUE THREAD

**Issue by kingtiger2** [macrozheng/mall#170]
https://github.com/macrozheng/mall/issues/159

对于这个问题,https://blog.csdn.net/wxd_1024/article/details/83549967
不同的消息给不同的延时时间,死信队列不是按照延时时间排序,而是入队列的顺序

**Comment by kingtiger2** [comment]
@macrozheng

**Comment by kingtiger2** [comment]
为什么要关闭帖子啊,这明显就不对,太不负责了!!!!

**Comment by zwallzhou** [comment]
哈哈，别认真
