### ISSUE TITLE
每个项目里都有一个数据库配置，是否可以简化这种配置呢？

### ISSUE THREAD

**Issue by tianshaokai** [macrozheng/mall#171]
1.如题

**Comment by hyz951226** [comment]
Spring-cloud-config?

**Comment by tianshaokai** [comment]
@hyz951226 嗯，应该是Spring-cloud 云

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/61356733-92f54e00-a8a9-11e9-8ceb-dc7eba4512a6.png)
找不到类 为啥会 无法注入

**Comment by tianshaokai** [comment]
![image](https://user-images.githubusercontent.com/6706496/61356797-b5876700-a8a9-11e9-81b3-8589d0507d53.png)
为啥会无法注入，找不到类

**Comment by ma-xiaoliang** [comment]
这是你 idea设置的问题 




发自网易邮箱大师
在2019年7月17日 15:45，田绍凯<notifications@github.com> 写道：


为啥会无法注入，找不到类

**Comment by tianshaokai** [comment]
我刚安装了lombok这个插件

**Comment by pqo169** [comment]
为什么安装会提示失败是不是有些版本不兼容




------------------ 原始邮件 ------------------
发件人: "田绍凯"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 下午3:54
收件人: "macrozheng/mall"<mall@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [macrozheng/mall] 每个项目里都有一个数据库配置，是否可以简化这种配置呢？ (#171)




我刚安装了lombok这个插件

**Comment by tianshaokai** [comment]
@ma-xiaoliang  大佬我的idea该如何配置

**Comment by ma-xiaoliang** [comment]
File -- Settings -- Inspections。在Spring Core -- Autowring for Bean Class 中，

将Severity的级别由之前的error改成warning



发自网易邮箱大师
在2019年7月17日 16:00，田绍凯<notifications@github.com> 写道：

@ma-xiaoliang 大佬我的idea该如何配置

**Comment by tianshaokai** [comment]
@ma-xiaoliang  谢谢

**Comment by hyz951226** [comment]
可以close掉了吧

**Comment by tianshaokai** [comment]
嗯，不过希望作者可以修改一下数据库配置，目前项目里好多数据库连接配置
