### ISSUE TITLE
请问未来有计划改造成微服务吗？

### ISSUE THREAD

**Issue by TrZoey** [macrozheng/mall#174]
如题

**Comment by macrozheng** [comment]
有考虑过，会出个SpringCloud版本。

**Comment by gobibigo** [comment]
https://github.com/YourFantasy/mallcloud-platform   这个也是作者的吗

**Comment by wxpp** [comment]
这种 一个project多个module的项目构造 最后上线的话 只出一个jar包就好了么？

**Comment by littileAn** [comment]
> 有考虑过，会出个SpringCloud版本。
有考虑过使用grpc吗

**Comment by jetablezhu** [comment]
那还得有服务治理了，作者一个人累死了:innocent:

**Comment by macrozheng** [comment]
已经改了：https://github.com/macrozheng/mall-swarm
