### ISSUE TITLE
The specified target project directory mall-mbg\src\main\java does not exist

### ISSUE THREAD

**Issue by yrong** [macrozheng/mall#177]
linux环境下开发环境

-        <javaModelGenerator targetPackage="com.macro.mall.model" targetProject="mall-mbg\src\main\java"/>
+       <javaModelGenerator targetPackage="com.macro.mall.model" targetProject="mall-mbg/src/main/java"/>

**Comment by macrozheng** [comment]
自行修改下就好了

**Comment by tanhaican** [comment]
Mac 下面报该错时，将路径里面的反斜杠（\)改为斜杠（/）即可。如：
mall-mbg\src\main\java  -->  mall-mbg/src/main/java

**Comment by AaronWing** [comment]
> Mac 下面报该错时，将路径里面的反斜杠（)改为斜杠（/）即可。如：
> mall-mbg\src\main\java --> mall-mbg/src/main/java

不管用

**Comment by innerx** [comment]
可以临时改成绝对路径
