### ISSUE TITLE
库存锁定的错误？

### ISSUE THREAD

**Issue by xuechangjiang** [macrozheng/mall#187]
生成订单时进行库存锁定
源码：
 `//获取购物车及优惠信息
        UmsMember currentMember = memberService.getCurrentMember();
        List<CartPromotionItem> cartPromotionItemList ==cartItemService.listPromotion(currentMember.getId());
//进行库存锁定
        lockStock(cartPromotionItemList);`
作者在文档中写道：
库存的锁定：库存从获取购物车优惠信息时就已经从pms_sku_stock表中查询出来了，lock_stock字段表示锁定库存的数量，会员看到的商品数量为真实库存减去锁定库存；
但是用户购买时可能只选择购物车中的一部分商品下单啊，但是源码里好像把购物车中所有的商品都锁定了，不应该是只锁定已经下单的商品吗

**Comment by macrozheng** [comment]
目前购物车只能下单所有商品，暂时还不支持下单指定商品。
