### ISSUE TITLE
app前台项目

### ISSUE THREAD

**Issue by dibingfa** [macrozheng/mall#197]
大佬，app前台项目代码什么时候出炉呀，期待中

**Comment by xuzhijvn** [comment]
大佬，app前台项目代码什么时候出炉呀，期待中

**Comment by ruifly2012** [comment]
大佬，app前台项目代码什么时候出炉呀，期待中

**Comment by softsrc** [comment]
嗯，太期待了

**Comment by softsrc** [comment]
先把仓库建起来，大家一起使劲也行啊

**Comment by wxpp** [comment]
https://github.com/macrozheng/mall-admin-web

**Comment by f54701771** [comment]
大佬，app前台项目代码什么时候出炉呀，期待中

**Comment by jetablezhu** [comment]
同问，app代码啥时候能放出来呢？o(*￣︶￣*)o

**Comment by 123nww** [comment]
大佬,app什么时候开源,

**Comment by aaa7636602** [comment]
还有 pc前台商城 也没有。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "macrozheng/mall"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月15日(星期三) 上午9:29
收件人:&nbsp;"macrozheng/mall"<mall@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [macrozheng/mall] app前台项目 (#197)





 
大佬,app什么时候开源,

**Comment by kangchengkun** [comment]
app 把地址搞出来，一起撸啊撸呗
