### ISSUE TITLE
商家入驻系统有开发计划吗？

### ISSUE THREAD

**Issue by ruifly2012** [macrozheng/mall#199]

**Comment by cuizhaojin** [comment]
工程太大了，一个人搞要累死了。

**Comment by ThinkingInMe** [comment]
@cuizhaojin 那么多人呢

**Comment by xxl-cc** [comment]
同问呢。

**Comment by jetablezhu** [comment]
商家入驻？淘宝模式么

**Comment by zyfsuzy** [comment]
应该是合作对接

**Comment by taoliunian** [comment]
有
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"zyfsuzy"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月15日(星期五) 下午3:44
 收件人:&nbsp;"macrozheng/mall"<mall@noreply.github.com&gt;;
 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
 主题:&nbsp;Re: [macrozheng/mall] 商家入驻系统有开发计划吗？ (#199)

 

 
应该是合作对接

**Comment by gugugubo** [comment]
同求啊！有没有同志搞呀！？
