### ISSUE TITLE
powerdesigner 16.5 打不开pdm文件

### ISSUE THREAD

**Issue by wangjia2016** [macrozheng/mall#209]
powerdesigner 16.5 打不开pdm文件

PowerDesigner failed to read the file :
   E:\macrozheng\mall_pms.pdm.

**Comment by macrozheng** [comment]
可以打开的，就是加载比较慢，可能要1到2分钟

**Comment by wangjia2016** [comment]
![image](https://user-images.githubusercontent.com/16084076/66642576-9c474a00-ec4f-11e9-8ccb-f02d66f9638e.png)

打不开的，直接报错了
@macrozheng
