### ISSUE TITLE
我刚刚入门，我想问下这个项目的sql语句写在哪里

### ISSUE THREAD

**Issue by lixiusen** [macrozheng/mall#21]

**Comment by iterge** [comment]
本项目是写在mall/mall-admin/src/main/resources/dao/下面相应的xml文件里。其他项目也是一样，详细了解建议先看下mybatis网址：http://www.mybatis.org/mybatis-3/zh/index.html
还有哪里不懂的可以问我，知无不言 一起学习~

**Comment by lixiusen** [comment]
> 本项目是写在mall/mall-admin/src/main/resources/dao/下面相应的xml文件里。其他项目也是一样，详细了解建议先看下mybatis网址：http://www.mybatis.org/mybatis-3/zh/index.html 还有哪里不懂的可以问我，知无不言 一起学习~ At 2018-12-29 14:52:47, "lixiusen" <notifications@github.com> wrote: — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

原来如此，谢谢你
