### ISSUE TITLE
为什么在swagger上已经登录了查询的时候还是报401

### ISSUE THREAD

**Issue by wenlou** [macrozheng/mall#210]
成功登录，已经返回token了，数据库里也插入了登录记录，为什么查询的时候还是报401？是我的操作不对吗？点最右边的Authorize，填入token依旧报401

**Comment by macrozheng** [comment]
你可以看下这个[mall整合SpringSecurity和JWT实现认证和授权（二）](https://juejin.im/post/5cfa0933f265da1b8f1ab2da)，头信息是由tokenHead和token拼接而成的。
