### ISSUE TITLE
linux部署elasticsearch报错

### ISSUE THREAD

**Issue by kimi77** [macrozheng/mall#211]
按照文档写的在执行了
docker run -p 9200:9200 -p 9300:9300 --name elasticsearch \
-e "discovery.type=single-node" \
-e "cluster.name=elasticsearch" \
-v /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins \
-v /mydata/elasticsearch/data:/usr/share/elasticsearch/data \
-d elasticsearch:6.4.0
之后返回了如下错误：

docker: Error response from daemon: driver failed programming external connectivity on endpoint elasticsearch (400e08214eba86f346854824cdb4037caaa2688de3747b799d48227880995d2f):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 9300 -j DNAT --to-destination 172.18.0.6:9300 ! -i docker0: iptables: No chain/target/match by that name.

有办法解决不

**Comment by yitianhaoaren** [comment]
我这也遇到了

**Comment by aboutZZ** [comment]
@kimi77  @yitianhaoaren 应该是因为没有打开iptables防火墙
