### ISSUE TITLE
分析代码遇到的几个问题

### ISSUE THREAD

**Issue by itheimaxia** [macrozheng/mall#220]
1.权限的性能问题，JWT携带的信息只有用户名，没有用户的权限，导致每次接口调用都需要访问数据库
2.确认单和订单没有结合起来，而且必定下单购物车中的所有商品
3.订单生成时的sku库存判断有误，应该算上quantity，比如现在100个库存，0个锁定，我下单110个还可以成功

**Comment by itheimaxia** [comment]
1.`docker-compose-env.yml`脚本中elasticsearch缺少端口映射:
ports:
      - 9200:9200
      - 9300:9300

由于使用java客户端访问elasticsearch所以会使用到tcp连接端口9300。

2.还需要对plugins文件夹进行权限设置:
# 创建目录
mkdir /mydata/elasticsearch/data/
# 创建并改变该目录权限
chmod 777 /mydata/elasticsearch/data
# 创建目录
mkdir /mydata/elasticsearch/plugins/
# 创建并改变该目录权限
chmod 777 /mydata/elasticsearch/plugins

**Comment by itheimaxia** [comment]
rabbitmq延迟消息取消订单代码还在，但是应该没用到了
使用springtask定时清理订单

**Comment by jetablezhu** [comment]
一起行动起来啊，找到问题，提出方案，提交修改代码，让这个项目更好起来
