### ISSUE TITLE
参数校验问题

### ISSUE THREAD

**Issue by mrbook1122** [macrozheng/mall#229]
UmsAdminController中请求方法的参数缺少`@Valid`注解，比如register方法，我本地测试时只有给UmsAdminParam umsAdminParam参数添加`@Valid`之后，后端才能对错误参数返回相应的信息

**Comment by macrozheng** [comment]
是的，不过那个参数校验目前版本已经不在使用了，还是通过自行校验，然后抛出异常，进行全局异常捕获来校验比较好。
