### ISSUE TITLE
关于mall-admin-web订单详情的疑惑

### ISSUE THREAD

**Issue by caojiele** [macrozheng/mall#230]
我想问下在**订单详情**中的**商品信息**怎么才能显示？

![图片](https://cdn.nlark.com/yuque/0/2019/png/338441/1574251898237-290bd642-3394-46aa-938b-715ded6fd4db.png)

**Comment by macrozheng** [comment]
你看这个订单就是可以显示的：http://www.macrozheng.com/admin/#/oms/orderDetail?id=12

**Comment by caojiele** [comment]
> 你看这个订单就是可以显示的：http://www.macrozheng.com/admin/#/oms/orderDetail?id=12
嗯，这个我知道。所以我想问下怎么显示的？我的接口里面都有这些参数，是不是前端回调后要返回给后台管理这边？
