### ISSUE TITLE
这个会员管理，还有权限管理，没有啊

### ISSUE THREAD

**Issue by JackZhangYu** [macrozheng/mall#238]
现在这个模块在那里

**Comment by JackZhangYu** [comment]
看到了，进度还没做完

**Comment by JackZhangYu** [comment]
![image](https://user-images.githubusercontent.com/20717502/70126415-ec70e480-16b3-11ea-81c8-43ddab9a441f.png)
我加的左侧菜单栏，顶级的不显示

**Comment by JackZhangYu** [comment]
@macrozheng  这是我加的路由代码，和前端的显示效果
![微信图片_20191204163544](https://user-images.githubusercontent.com/20717502/70126653-6d2fe080-16b4-11ea-9b99-7315cd4c493a.png)
![微信图片_20191204163613](https://user-images.githubusercontent.com/20717502/70126655-6dc87700-16b4-11ea-8974-8c19aa6a93e4.png)

**Comment by wangjia2016** [comment]
楼上的图没显示出来

**Comment by JackZhangYu** [comment]
问题已经解决了，加了一个强制显示就好了
