### ISSUE TITLE
老哥你mybaits-generator的代码是怎么自动生成的？

### ISSUE THREAD

**Issue by ChinaXiaoMing** [macrozheng/mall#260]

**Comment by Mr-jackchen** [comment]
现在都用mybatis-plus了，自动生成直接看官网的API最简单

**Comment by wangzhaoming132-gif** [comment]
> 现在都用mybatis-plus了，自动生成直接看官网的API最简单

mybatis-plus比 mybatis-generator 好用吗？

**Comment by Mr-jackchen** [comment]
> > 现在都用mybatis-plus了，自动生成直接看官网的API最简单
> 
> mybatis-plus比 mybatis-generator 好用吗？

mybatis的自动生成工具在官网上有，如果你们系统中引入了mybatisplus，可以用mybatisplus，对mybatis的封装，开发效率会更高
