### ISSUE TITLE
潜在帐号密码泄漏风险

### ISSUE THREAD

**Issue by huisnotacouncillor** [macrozheng/mall#261]
@macrozheng 大神您好，mall-admin-web项目登录模块把帐号和密码直接明文存在Cookie里面，存在泄漏风险
所在工程：mall-admin-web
所在文件：src/views/login/index.vue
所在行数：135-136行
截图：如下
![image](https://user-images.githubusercontent.com/45624731/71712963-8e662700-2e42-11ea-932a-5a3180144d84.png)

**Comment by XiaomingX** [comment]
好垃圾的项目，竟然还这么多star
