### ISSUE TITLE
Could not find artifact com.macro.mall:mall-mbg:pom:1.0-SNAPSHOT

### ISSUE THREAD

**Issue by sunlight2728** [macrozheng/mall#279]
照着文档 package 构建mall-admin 项目的时候出现这个问题
Could not find artifact com.macro.mall:mall-mbg:pom:1.0-SNAPSHOT

**Comment by sunlight2728** [comment]
mall-mbg  这个jar包咋弄

**Comment by macrozheng** [comment]
在mall-mbg模块上通过使用 maven install 命令来生成。
