### ISSUE TITLE
pull access denied for mall/mall-admin?

### ISSUE THREAD

**Issue by zhangtianai** [macrozheng/mall#283]
root@ip-172-31-2-74:~/mall/document/docker# docker-compose -f docker-compose-app.yml up -d
WARNING: Found orphan containers (elasticsearch, redis, kibana, rabbitmq, mongo, nginx, mysql) for this project. If you removed or renamed this servi
ce in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Pulling mall-admin (mall/mall-admin:1.0-SNAPSHOT)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your dat
a before continuing.

Continue with the new image? [yN]n
ERROR: pull access denied for mall/mall-admin, repository does not exist or may require 'docker login': denied: requested access to the resource is d
enied

**Comment by macrozheng** [comment]
需要自己打包，具体参考[《使用Maven插件为SpringBoot应用构建Docker镜像》](http://www.macrozheng.com/#/reference/docker_maven)
