### ISSUE TITLE
是不是刚从其他项目抠出来的？哈哈，还有很多要完善的地方，还不是真正的微服务

### ISSUE THREAD

**Issue by RexFang** [macrozheng/mall#29]
是不是刚从其他项目抠出来的？哈哈，还有很多要完善的地方，还不是真正的微服务

**Comment by macrozheng** [comment]
你可以看下这个项目的提交记录，从2018年4月一直写到现在的，怎么会是从其他项目里面抠出来的

**Comment by RexFang** [comment]
> 你可以看下这个项目的提交记录，从2018年4月一直写到现在的，怎么会是从其他项目里面抠出来的

没有恶意哈，如果给你造成困扰请忽略
