### ISSUE TITLE
Whitelabel Error Page This application has no explicit mapping for /error, so you are seeing this as a fallback.  Fri Mar 06 11:11:15 UTC 2020 There was an unexpected error (type=Bad Request, status=400). Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "login"

### ISSUE THREAD

**Issue by COOLMSF** [macrozheng/mall#301]
你好， 后端搭建完后访问 8080/admin/login 出现错误：

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Mar 06 11:19:18 UTC 2020
There was an unexpected error (type=Bad Request, status=400).
Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "login"

**Comment by goodfree** [comment]
我也出现这个错误，请问你是怎么解决的
