### ISSUE TITLE
获取可用积分抵扣金额的疑问

### ISSUE THREAD

**Issue by realljt** [macrozheng/mall#306]
在这里，获取可用积分抵扣金额的方法：
BigDecimal integrationAmount = new BigDecimal(useIntegration).divide(new BigDecimal(integrationConsumeSetting.getUseUnit()), 2, RoundingMode.HALF_EVEN);

为什么不是 useIntegration 除以 deductionPerAmount？

**Comment by macrozheng** [comment]
貌似都可以
