### ISSUE TITLE
docker-compose 在linux上部署，elasticsearch自动退出

### ISSUE THREAD

**Issue by snailccc** [macrozheng/mall#322]

**Comment by snailccc** [comment]
能够使用docker run正常启动，但是启动后立刻自动退出

**Comment by gitGksgk** [comment]
@snailccc  可能是内存不足，docker for windows 默认1024内存不够跑mall全家桶的，加多500M即可

**Comment by gitGksgk** [comment]
@snailccc  
登进去这个docker-compose创建的es机子看，
`docker run -it --entrypoint bash --privileged elasticsearch:6.4.0`
加privileged 是为了sysctl改时不报 read only file system 的错误
还是有[mall在Linux环境下的部署（基于Docker容器）](http://www.macrozheng.com/#/deploy/mall_deploy_docker?id=elasticsearch%e5%ae%89%e8%a3%85) 里说的es两个问题，要改.即data文件权限，和vm.max_map_count修改
直接改了data
`chmod 777 data
sysctl -w vm.max_map_count=261244
`

改完后再运行，终于起来了，吃了800M内存..

**Comment by nEdAy** [comment]
mac 怎么设置vm.max_map_count=262144呀
