### ISSUE TITLE
【校招社招】这套系统能用在生产吗？不想试一下吗

### ISSUE THREAD

**Issue by Nerom** [macrozheng/mall#323]
阿里直招，社招校招均有，BU囊括电商零售系统全链路，前端至交易、详情页，后端至仓储、履约，更有海外复杂场景等你实践，有意请邮件简历至 liuzhu.wlz#alibaba-inc.com
校招的潜力股，勇敢发来简历吧，会邀请进校招小群，定期分享写简历的技巧，更有优先面试的机会

公司/团队介绍
我们是阿里巴巴集团新零售技术旗下供应链技术国际化团队，我们致力于通过世界一流的全球化技术服务来自全球10亿+的海外消费者，为全球消费者带去极致的购物体验，让买全球卖全球的使命落地成为普惠全球的显示图景。我们服务的业务实体有 lazada、AliExpress、天猫海外、Daraz、Trendyol等平台。

联系方式
邮箱： liuzhu.wlz#alibaba-inc.com

**Comment by aboutZZ** [comment]
这里不是你打广告的地方，自己删了issue吧
