### ISSUE TITLE
登录时500错误

### ISSUE THREAD

**Issue by provenpeng** [macrozheng/mall#338]
java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
.....
c.m.m.s.component.DynamicSecurityFilter  : Public object - authentication not attempted

**Comment by milexin** [comment]
发送自我的三星盖乐世智能手机。
4

-------- 原始信息 --------
发件人： provenpeng <notifications@github.com>
日期: 2020/5/6 01:21 (GMT+08:00)
收件人： macrozheng/mall <mall@noreply.github.com>
抄送： Subscribed <subscribed@noreply.github.com>
主题： [macrozheng/mall] 登录时500错误 (#338)


java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter

**Comment by sunnyliujing** [comment]
可参考 https://www.cnblogs.com/it-tsz/p/11749651.html

**Comment by macrozheng** [comment]
参考楼上解决方法即可
