### ISSUE TITLE
mall.sql  注释错别字

### ISSUE THREAD

**Issue by himcs** [macrozheng/mall#347]
CREATE TABLE `sms_coupon` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `type` int(1) DEFAULT NULL COMMENT '优惠卷类型；0->全场赠券；1->会员赠券；2->购物赠券；3->注册赠券',。。。
  
应为 优惠券

**Comment by lg-senlk** [comment]
真想戳瞎你这双善于发现的眼睛  哈哈哈

**Comment by lx275956146** [comment]
666

**Comment by aaa7636602** [comment]
此人是人才，建议把他提为contributor

**Comment by 1124875284** [comment]
哈哈

**Comment by luzhongyun** [comment]
精细
