### ISSUE TITLE
Error:(4,33) java: 程序包com.macro.mall.common.api不存在是为什么？

### ISSUE THREAD

**Issue by githubjisiqi** [macrozheng/mall#355]
在最后打算用docker上传服务器的时候进行install和package
Error:(4,33) java: 程序包com.macro.mall.common.api不存在

**Comment by macrozheng** [comment]
mall-common模块需要使用`maven install`安装到本地仓库，具体参考[《mall在Linux环境下的自动化部署（基于Jenkins）》](http://www.macrozheng.com/#/deploy/mall_deploy_jenkins)中的构建部分。
