### ISSUE TITLE
就想问问前台商城啥时候上

### ISSUE THREAD

**Issue by dqt19921207** [macrozheng/mall#357]

**Comment by StarLeeHaut** [comment]
同问

**Comment by aaa7636602** [comment]
前台商城pc端快了吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"StarLee"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月26日(星期五) 下午3:42
收件人:&nbsp;"macrozheng/mall"<mall@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [macrozheng/mall] 就想问问前台商城啥时候上 (#357)





 
同问
