### ISSUE TITLE
订单状态变更逻辑可以更严谨

### ISSUE THREAD

**Issue by whbhhh** [macrozheng/mall#362]
订单的状态变更逻辑只是数据库的标识更改，
这样人为在数据库上直接改状态，这个订单的流程就会出现错乱
一般订单状态的变更是需要事件驱动，而不是主动去变更吧，这部分可以用DDD思想来设计，引入状态自检机制，即使人为数据库修改数据，订单也不会走流程，而是抛出异常，或者作出处理

**Comment by theonLyTao** [comment]
订单的状态决定了对外的展现形式，无非各自状态下的各种数据的一致性需要保证（也就是当前状态应该有什么样的数据），直接更改数据库的操作在生产环境一般是不允许的，没什么自检的必要

**Comment by bluce-clj** [comment]
既然可以提出，就去分支实践解决呀

**Comment by wangjia2016** [comment]
期待楼主的实践

**Comment by jrsen** [comment]
```Write and fuck the code!```
