### ISSUE TITLE
登录和注册的问题

### ISSUE THREAD

**Issue by xiaojianchi** [macrozheng/mall#363]
把前台和后台都打开以后。
访问 后端的 8080，提示 未登录或token过期
访问前端的 8090，只有登录和体验账号。
我想问一下怎么注册？

**Comment by macrozheng** [comment]
暂时没有注册功能，需要管理员登录后添加。

**Comment by zwd13122889** [comment]
> 暂时没有注册功能，需要管理员登录后添加。

这个密码是啥加密的   我用md5怎么解密不了
