### ISSUE TITLE
关于refreshToken实现

### ISSUE THREAD

**Issue by gpqhl0071** [macrozheng/mall#369]
看了下后端代码，有提供refreshToken ，刷新鉴权token的接口，但是在前端，没有找到实现的功能？

**Comment by MarsZone** [comment]
哈，看来不止我一个人有疑问。。那就是作者懒得在前端写了,但是这功能写的还是挺全的。

**Comment by gpqhl0071** [comment]
嗯，等作者回复，花儿都谢了，很无语~~~~

**Comment by achunCoding** [comment]
刷新token逻辑是怎么样的，快过期的时候 然后 检测 刷新吗。

**Comment by daidai21** [comment]
例如1min过期，每59s就去请求下，获取新的token吧，前端自己定时轮训的

**Comment by gpqhl0071** [comment]
我这边前端，有自己的实现方式，当用户携带accressToken请求如果失效时，前端会携带refreshToken去获取新的accressToken。

**Comment by achunCoding** [comment]
可以参考这篇博客。[刷新token](https://juejin.im/post/6854573219119104014)  后端会返回刷新token和accessToken 当accessToken过期之后 携带刷新token去重新请求accessToken

**Comment by LDTeemo** [comment]
我很想知道，后台程序在哪里判断token是否过期，没看到这部分逻辑呀
