### ISSUE TITLE
密码明文传输有安全性问题

### ISSUE THREAD

**Issue by Chinvi** [macrozheng/mall#37]
建议密码最好在前端密文传输到后端，后端怎么处理都行，但是传输过程中出现明文很明显有安全性问题。

**Comment by zhbitcxy** [comment]
登录页面使用https连接也可以

**Comment by liunaijie** [comment]
我现在有一个场景是批量导入用户信息，然后后台设置默认密码。但是如果前台加密的话就会判断为密码错误，是不是要在批量设置密码的时候与前台使用一样的加密方式然后再进行处理，或者有什么更好的解决方法呢？求解。

**Comment by coding4nobody** [comment]
> 我现在有一个场景是批量导入用户信息，然后后台设置默认密码。但是如果前台加密的话就会判断为密码错误，是不是要在批量设置密码的时候与前台使用一样的加密方式然后再进行处理，或者有什么更好的解决方法呢？求解。

你可以试试改数据库表结构（加一个default value，不过我怕你会被dba打死）或者导入数据的时候，统一将一个加密后的密码设置当默认参数，然后update到数据库里面

**Comment by liunaijie** [comment]
> > 我现在有一个场景是批量导入用户信息，然后后台设置默认密码。但是如果前台加密的话就会判断为密码错误，是不是要在批量设置密码的时候与前台使用一样的加密方式然后再进行处理，或者有什么更好的解决方法呢？求解。
> 
> 你可以试试改数据库表结构（加一个default value，不过我怕你会被dba打死）或者导入数据的时候，统一将一个加密后的密码设置当默认参数，然后update到数据库里面
我现在是通过excel导入用户信息时，后台默认设置密码，然后前台登录的时候会进行加密，然后我后台也会再次加密然后与数据库对比。由于批量导入的时候前台没有加密过，所以这时密码不一致，会判断为密码错误。我现在的解决办法是导入的时候走一次前台加密，走一次后台加密然后保存数据库
