### ISSUE TITLE
关于超时订单处理问题

### ISSUE THREAD

**Issue by qxxg** [macrozheng/mall#371]
简单的看过了代码之后发现再超时订单处理这块有两个地方都有处理。一个是OrderTimeOutCancelTask这个类：这个类是一个定时任务会定时处理超过10分钟的订单。另一个是CancelOrderReceiver这个类：这个类是一个rabbitMq的死信队列，在生成订单的时候会自动往死信队列发送一个延时消息。超时订单就会释放。

我想问下，这两个地方是不是会冲突。还是故意这样设置的 谢谢

**Comment by macrozheng** [comment]
最初是用的定时任务，后来加入了消息队列，只用消息队列即可
