### ISSUE TITLE
生成子订单order_item的时候，没有指定相应的订单id

### ISSUE THREAD

**Issue by lm-lan** [macrozheng/mall#378]
//生成订单号
1        order.setOrderSn(generateOrderSn(order));
2       //设置自动收货天数
3      List<OmsOrderSetting> orderSettings = orderSettingMapper.selectByExample(new OmsOrderSettingExample());
4        if(CollUtil.isNotEmpty(orderSettings)){
5            order.setAutoConfirmDay(orderSettings.get(0).getConfirmOvertime());
6       }
7      // TODO: 2018/9/3 bill_*,delivery_*
8        //插入order表和order_item表
9       orderMapper.insert(order);
10       for (OmsOrderItem orderItem : orderItemList) {
11          orderItem.setOrderId(order.getId());
12         orderItem.setOrderSn(order.getOrderSn());
        }

底 9行，底11行
订单id直接从，order里拿，此时order里的id是空的

**Comment by hexf3** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    ‘’’[    z
    
        
            
        
    
    
          
        
            

    
        
    
     
    

    在2020年07月11日 17:37，lm-lan<notifications@github.com> 写道： 




//生成订单号

    order.setOrderSn(generateOrderSn(order));

    //设置自动收货天数

    List<OmsOrderSetting> orderSettings = orderSettingMapper.selectByExample(new OmsOrderSettingExample());

    if(CollUtil.isNotEmpty(orderSettings)){

        order.setAutoConfirmDay(orderSettings.get(0).getConfirmOvertime());

    }

    // TODO: 2018/9/3 bill_*,delivery_*

    //插入order表和order_item表

    **orderMapper.insert(order);**

    for (OmsOrderItem orderItem : orderItemList) {

        orderItem.setOrderId(**order.getId()**);

        orderItem.setOrderSn(order.getOrderSn());

    }



订单id直接从，order里拿，此时order里的id是空的

**Comment by lm-lan** [comment]
已解决
