### ISSUE TITLE
Redis缓存切面类

### ISSUE THREAD

**Issue by loserwangzhi** [macrozheng/mall#384]
RedisCacheAspect.java下切入点配置

@Pointcut("execution(public * com.macro.mall.portal.service.*CacheService.*(..)) || execution(public * com.macro.mall.service.*CacheService.*(..))")

路径不正确 提示红色

**Comment by macrozheng** [comment]
mall-security是不会被单独使用的，当被mall-admin或mall-portal模块使用时，这个切面就可以找到对应的路径了。
