### ISSUE TITLE
请问logstash 无法在es中创建索引是为什么？

### ISSUE THREAD

**Issue by zrd1314** [macrozheng/mall#392]
我的logstash 启动了，也是按照你写的步骤做的，但是就是无法在logstash中自动创建springboot-logstash-%{+YYYY.MM.dd} 类型
的索引

**Comment by xyw1042971947** [comment]
logstash版本问题，他之前代码里面4.8   需要换成5.2以

**Comment by macrozheng** [comment]
`logstash-logback-encoder`插件已经升级
