### ISSUE TITLE
UmsAdminController 注册用户，

### ISSUE THREAD

**Issue by fangtenglong** [macrozheng/mall#394]
@ApiOperation(value = "用户注册")
    @RequestMapping(value = "/register", method = RequestMethod.POST)
    @ResponseBody
    public CommonResult<UmsAdmin> register(@RequestBody UmsAdminParam umsAdminParam, BindingResult result) {
        UmsAdmin umsAdmin = adminService.register(umsAdminParam);
        if (umsAdmin == null) {
//这里没有return ，前端如何处理，注册失败呢？
            CommonResult.failed();
        }
        return CommonResult.success(umsAdmin);
    }

**Comment by macrozheng** [comment]
需要加个return，已经修复
