### ISSUE TITLE
ums_member表，字段英文应该是拼错了。。

### ISSUE THREAD

**Issue by MarsZone** [macrozheng/mall#395]
`luckey_count` int(11) DEFAULT NULL COMMENT '剩余抽奖次数',

应该是lucky 吧。。。

**Comment by bloodstorm** [comment]
。。好语法



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mars"<notifications@github.com&gt;; 
发送时间: 2020年8月14日(星期五) 晚上9:51
收件人: "macrozheng/mall"<mall@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [macrozheng/mall] ums_member表，字段英文应该是拼错了。。 (#395)





 
luckey_count int(11) DEFAULT NULL COMMENT '剩余抽奖次数',
 
应该是lucky 吧。。。

**Comment by qijinkui** [comment]
大兄弟，数据库的sql文件 怎么可以获取到呀
