### ISSUE TITLE
如果 search 模块和 portal 模块接入logstash,怎么区分 admin/portal/search 模块日志呢

### ISSUE THREAD

**Issue by sunyajie0829** [macrozheng/mall#403]

**Comment by sunyajie0829** [comment]
目前我采用4560/4561/4562 分别对应到 admin/portal/search 模块上来区分日志,type 修改为对应的admin/portal/search

**Comment by fangdengfu** [comment]
在日志系统中，将自己的serviceId写进去

**Comment by sunyajie0829** [comment]
> 在日志系统中，将自己的serviceId写进去

非常感谢,有想过这个方法,但是要修改日志,不过也应该这么做
