### ISSUE TITLE
请问 像DTO对应的xml文件（如：OmsOrderDao.xml） 手动写还是使用工具生成的啊？

### ISSUE THREAD

**Issue by qinjiefree** [macrozheng/mall#408]

**Comment by daidai21** [comment]
IDEA有代码提示的，自己手写的，但是是自己手写的；这就是数据库这块的逻辑
@qinjiefree

**Comment by daidai21** [comment]
OmsOrderDao.xml
对应的文件是这个：
https://github.com/macrozheng/mall/blob/master/mall-admin/src/main/java/com/macro/mall/dao/OmsOrderDao.java

**Comment by qinjiefree** [comment]
> IDEA有代码提示的，自己手写的，但是是自己手写的；这就是数据库这块的逻辑
> @qinjiefree

好的，我猜着也是手动写的，毕竟跟业务逻辑有关的

**Comment by qinjiefree** [comment]
> OmsOrderDao.xml
> 对应的文件是这个：
> https://github.com/macrozheng/mall/blob/master/mall-admin/src/main/java/com/macro/mall/dao/OmsOrderDao.java

嗯嗯

**Comment by achunCoding** [comment]
有业务应该都要手写，除非是简单的增删改查。

**Comment by qinjiefree** [comment]
答案已经出来了，谢谢大家
