### ISSUE TITLE
昨天下载的项目跑不起来

### ISSUE THREAD

**Issue by qinguabao** [macrozheng/mall#411]
mall-admin 运行后，打不开 http://localhost:8080/swagger-ui.html。
难道 最新的源码有坑 ？分数那么高 ，还有这种错误？

**Comment by achunCoding** [comment]
报什么错，是插件没有下载吗、

**Comment by qinguabao** [comment]
代码没有报错 按照 部署文档 操作的

**Comment by qinguabao** [comment]
下载的 分布式的 代码 跑不起来，打不开 http://localhost:8080/swagger-ui.html。
下载  v1.0.1 的 代码 可以运行 。
你可以自己 试试下载最新代码 ，是否能打开  http://localhost:8080/swagger-ui.html .

**Comment by qinguabao** [comment]
单机版的正常 ，分布式版本问题大大

**Comment by bbf13** [comment]
我导进idea文件都是红的怎么回事啊

**Comment by qinguabao** [comment]
lombok 安装没有 ？

**Comment by macrozheng** [comment]
mall-swarm采用网关聚合API文档的形式，使用的是knife4j，接口文档访问地址为：[http://localhost:8201/doc.html](http://localhost:8201/doc.html)，具体参考[mall-swarm在Windows环境下的部署](http://www.macrozheng.com/#/deploy/mall_swarm_deploy_windows)。
