### ISSUE TITLE
假设新增某个用户信息时，用户名不能为空，后台一般是@NotNull注解，但是MBG生产的model怎么动态生成@NotNull注解

### ISSUE THREAD

**Issue by qinjiefree** [macrozheng/mall#412]

**Comment by macrozheng** [comment]
可以在[CommentGenerator](https://github.com/macrozheng/mall/blob/master/mall-mbg/src/main/java/com/macro/mall/CommentGenerator.java)类的`addFieldComment`方法中修改实现，参考`@ApiModelProperty`注解的生成方法即可，方法参数中`IntrospectedColumn`类的`nullable`属性可用于判断数据库字段是否允许为空。
