### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by bestming** [macrozheng/mall#414]
大佬发个支付宝、微信、PayPal 收款码吧，开源不易，大伙打赏才能让开源者的热情不会慢慢消磨殆尽。

I suggest you send a payment code of alipay, WeChat and PayPal. It is not easy to open source. Only by giving rewards can we keep the enthusiasm of open source users from fading away.

**Comment by macrozheng** [comment]
多谢支持，收款码就不发了。
