### ISSUE TITLE
登录验证密码时抛出的异常没有捕获

### ISSUE THREAD

**Issue by zzjzzy** [macrozheng/mall#417]
UmsAdminServiceImpl中的login方法，Asserts.fail会抛出ApiException，这个异常没有被catch，如果密码输入错误，会导致接口直接返回500

` 
       try {
            UserDetails userDetails = loadUserByUsername(username);
            if(!passwordEncoder.matches(password,userDetails.getPassword())){
                Asserts.fail("密码不正确");
            }
            if(!userDetails.isEnabled()){
                Asserts.fail("帐号已被禁用");
            }
            UsernamePasswordAuthenticationToken authentication = new UsernamePasswordAuthenticationToken(userDetails, null, userDetails.getAuthorities());
            SecurityContextHolder.getContext().setAuthentication(authentication);
            token = jwtTokenUtils.generateToken(userDetails);
//            updateLoginTimeByUsername(username);
//            insertLoginLog(username);
        } catch (AuthenticationException e) {
            LOGGER.warn("登录异常:{}", e.getMessage());
        }
 `

![image](https://user-images.githubusercontent.com/38907165/93887923-e23ed600-fd19-11ea-9ca6-11c5d5e3aefe.png)

**Comment by AimeSoleil** [comment]
抛出的`ApiException` 会统一通过`GlobalExceptionHandler`处理：https://github.com/macrozheng/mall/blob/afc258b14c21454b8a5da2755bb17c8b59f51fe0/mall-common/src/main/java/com/macro/mall/common/exception/GlobalExceptionHandler.java#L20

**Comment by zzjzzy** [comment]
好的，感谢回复！我是一步步仿照做的，还没做到全局异常处理这一块，还以为没有异常处理。不好意思



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "julian"<notifications@github.com&gt;; 
发送时间: 2020年9月23日(星期三) 中午11:22
收件人: "macrozheng/mall"<mall@noreply.github.com&gt;; 
抄送: "ivy"<2487584294@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [macrozheng/mall] 登录验证密码时抛出的异常没有捕获 (#417)





 
抛出的ApiException 会统一通过GlobalExceptionHandler处理：https://github.com/macrozheng/mall/blob/afc258b14c21454b8a5da2755bb17c8b59f51fe0/mall-common/src/main/java/com/macro/mall/common/exception/GlobalExceptionHandler.java#L20
