### ISSUE TITLE
希望能做成springcloud

### ISSUE THREAD

**Issue by shijunwang001** [macrozheng/mall#42]
springcloud是一个趋向，我希望研究一下

**Comment by nikorliu** [comment]
这个跟springcloud没什么关系吧

**Comment by liupeizhi** [comment]
单体应用和微服务的区别，大型系统从新开始做可以考虑SpringCloud，遗留系统就不必了

**Comment by Chowing** [comment]
看图片我感觉是要做成微服务

**Comment by moonncat** [comment]
> springcloud是一个趋向，我希望研究一下

我提了pull request 在 mall-search 模块了，增加了spring-clound的一些基础功能
