### ISSUE TITLE
商品销量的设计 sale 字段

### ISSUE THREAD

**Issue by wangjia2016** [macrozheng/mall#421]
1、商品表 我看有个字段 sale                 int comment '销量', 存的是销量，
这样设计不太合理吧，这样每个商品销售出去了 还得更新商品这个里面的值了，
商品退款了 还得去减掉这个值了，

这种更新 如果出现问题，就会导致销量不准确了

2、一些富文本字段 应该单独建表存储吧

**Comment by l0n9er** [comment]
这个项目是用来练手学习，真上生产够呛

**Comment by wangjia2016** [comment]
咋没回复 就给关闭了 啊 可以探讨一下
