### ISSUE TITLE
mall-portal 前台接口里面为啥会需要 MallSecurityConfig

### ISSUE THREAD

**Issue by wangjia2016** [macrozheng/mall#422]
![image](https://user-images.githubusercontent.com/16084076/94924378-fb9d0a80-04ef-11eb-8399-7a68b62eb3cf.png)

前台接口 应该不需要权限判断吧？
比如一个下单接口，会需要什么权限呢，

**Comment by macrozheng** [comment]
MallSecurityConfig是安全配置，可以同时配置权限和登录认证，前台接口中的登录认证需要配置。
