### ISSUE TITLE
项目采用mybatis-plus是个败笔

### ISSUE THREAD

**Issue by zhang145926** [macrozheng/mall#427]
项目中的分页采用mybatis-plus分页，针对复杂查询条件，且查询条件和数据列大部分都不一致时，这个框架会输出很多非必要数据，如果项目再引入mybatisHelper分页插件，两个分页插件会冲突，而且作者项目中使用的是plus，而在文档中写的是helper来做引导，很明显根本自己没有尝试同时引入两个分页插件

**Comment by autumn-chendq** [comment]
既然是开源就没有所谓的败笔，请问你有何大作让大家看看？？？

发自我的iPhone

在 2020年10月27日，00:08，zhang145926 <notifications@github.com> 写道：

﻿

项目中的分页采用mybatis-plus分页，针对复杂查询条件，且查询条件和数据列大部分都不一致时，这个框架会输出很多非必要数据，如果项目再引入mybatisHelper分页插件，两个分页插件会冲突，而且作者项目中使用的是plus，而在文档中写的是helper来做引导，很明显根本自己没有尝试同时引入两个分页插件

**Comment by xyting** [comment]
> 既然是开源就没有所谓的败笔，请问你有何大作让大家看看？？？ 

个人觉得这态度有点不友好，别人也只是说了自己的想法，我们可以不认同，但没有必要针锋相对。

**Comment by InuYasha000** [comment]
一言不合，十分暴躁，开源项目又不是每行代码都是精华，每个选择都是完美，程序员本来就要有自己的思考。

**Comment by xyting** [comment]
> 一言不合，十分暴躁，开源项目又不是每行代码都是精华，每个选择都是完美，程序员本来就要有自己的思考。

是的，每一行代码都需要推敲是自己的事，属于个人追求。

不过说实话，我刚开始想对这个项目PR，不过，因为改动太大，不打算合并进来，我替换了几个方面：
1. 更好的实现mall-security模块；
2. 替换成[MyBatis Dynamic SQL](https://mybatis.org/mybatis-dynamic-sql/docs/introduction.html)
3. 前端替换成了小程序

**Comment by xied75** [comment]
@xyting 既如此就可以借原主的宝地announce一下你的fork，让它们自然竞争啊。老外的项目都是这样发展起来的。我看了你的repo没找到，没开锁么？
