### ISSUE TITLE
关于permission的权限疑问

### ISSUE THREAD

**Issue by Sebastian-Getts** [macrozheng/mall#437]
发现项目只有ums_role_permission_relation和ums_admin_permission_relation以及ums_permission这几张表的定义，没有后续使用，具体的基于数据的读、改以及根据接口的细粒度权限控制如何实现呢？

**Comment by macrozheng** [comment]
目前这几张表已经不再使用了，权限功能具体参考：[《手把手教你搞定权限管理，结合Spring Security实现接口的动态权限控制！》](http://www.macrozheng.com/#/technology/permission_back)。

**Comment by xlkit456852** [comment]
如果还是有这样的需求：比如后台某个添加按钮或者操作按钮是需要通过权限判断是否显示的，那是不是还是用菜单表再增加一个type为按钮的来显示？如果是给到客户那边用这个后台，他们可能不会设置Ant资源路径的哦。。
