### ISSUE TITLE
mysql命名规范有些小错误

### ISSUE THREAD

**Issue by tujietg** [macrozheng/mall#44]
根据《阿里巴巴Java开发手册》里的mysql规约，唯一索引建议命名为uk_字段名，普通索引名则为idx_字段名。ums_member 这个表中的唯一索引用的是idx_字段名。就是不知道大佬是不是根据《阿里巴巴Java开发手册》来的～！

**Comment by macrozheng** [comment]
我参考了下，确实该这样
