### ISSUE TITLE
有关自动取消订单问题

### ISSUE THREAD

**Issue by imperfect-wqy** [macrozheng/mall#442]
自动取消超时订单是采用定时任务扫描，如果有到期订单，那就自动取消订单；但是取消单个超时订单的逻辑是根据orderId，获得订单的超时剩余时间，然后发给消息队列消费。所以取消单个订单的接口是什么时候调用呢，在支付成功的时候？还是说由用户手动点击？如果是用户的话，不应该是点击就应该执行取消订单的逻辑了吗？

**Comment by macrozheng** [comment]
定时任务和发送延迟消息是两种不同的取消订单方式，直接使用后者也是可以的。取消单个订单操作在下单接口中已经调用，无需自行调用，可以看到在OmsPortalOrderServiceImpl的generateOrder方法中已经调用。
