### ISSUE TITLE
商品属性应该属于商品还是商品分类

### ISSUE THREAD

**Issue by hdtopku** [macrozheng/mall#443]
### 作者的设计（将商品属性归属于商品分类）
其中一个好处是可以统一修改同一商品分类的属性名称。但也存在一定的弊端，比如：
1. 一个属性下有1000个商品，修改属性名称【容量】->【内存】，那需要遍历1000个商品，修改pms_sku的sp_data字段，如果有500个商品还想保留容量属性，这无疑给图三商品规格的维护增加了难度。
2. 同一分类的商品属性不一定一样（比如帽子分类的尺码属性，有的帽子有不同尺码S、M、X、L，有的帽子均码，没有无需尺码属性）。会给同一类型下的许多商品造成很多冗余。
![https://user-images.githubusercontent.com/14859466/101418038-e0071380-3927-11eb-8009-8e05529d6878.png](https://user-images.githubusercontent.com/14859466/101418038-e0071380-3927-11eb-8009-8e05529d6878.png)、
![https://user-images.githubusercontent.com/14859466/101418087-05941d00-3928-11eb-87d9-ac4d5637198f.png](https://user-images.githubusercontent.com/14859466/101418087-05941d00-3928-11eb-87d9-ac4d5637198f.png)

### 我的设计（将商品属性归属于商品spu）
> [国云商城](https://static-95f1970c-da88-4722-9673-897de6038fc7.bspapp.com/admin/index.html#/product/product)
用户名：test、密码：12345678
商品管理->商品管理->添加产品->添加规格
受到国云商城的启发，由于代码未部署到公网，参考国云商城即可

将属性归于商品的spu，这样的好处：
1. 每个商品的规格名称可以独立命名
2. 每个商品的规格可以独立增删，不依赖于商品分类

![https://user-images.githubusercontent.com/14859466/101421136-a554a980-392e-11eb-9724-e693bbd423b4.png](https://user-images.githubusercontent.com/14859466/101421136-a554a980-392e-11eb-9724-e693bbd423b4.png)

### 补充
这个问题一直困扰了我很久，也许是我某些地方没想到，望作者指点。

**Comment by CNAHYZ** [comment]
作者应该是参考淘宝的商品设置来的，只能根据分类下预设的规格模板来填写，不能自定义规格。如果没有这个限制，个人认为显然你的方法更灵活些

**Comment by macrozheng** [comment]
商品属性关联的是`pms_product_attribute_category`表（商品属性分类）而不是`pms_product_category`表（商品分类），比如说服饰分类下有帽子和上衣两种商品，你可以建立商品属性分类为`服饰-帽子`和`服饰-上衣`来定义属性。商品属性分类你可以理解为商品属性的模板，这样对于一堆同模板的商品可以复用。
