### ISSUE TITLE
XSS攻击问题

### ISSUE THREAD

**Issue by scruel** [macrozheng/mall#445]
使用 token 方式进行用户鉴权固然不错，可以预防 csrf 攻击，但是由于 cookies 是前端管理的，只能设置 httponly=false 以供前端 js 保存和读取，这种方式如果遭到 XSS 攻击，即可无遮拦获取到 token，项目中的 token 的有效期设置的很长，而即便设置的很短，也仍然会有权限泄露风险，一旦被利用后果不堪设想，请问这个方面项目是如何权衡的？
当然，使用 httponly 方式会导致跨域无法访问资源的问题，所以是考虑到 cookies 方式跨域麻烦的问题嘛？

**Comment by sixleaves** [comment]
这哪有万全的解决方案。你可以加个ip地址验证，不是常用ip让重新登入。但越是安全，客户端体验越差。
