### ISSUE TITLE
后台权限不能分配多个角色

### ISSUE THREAD

**Issue by YiwenXie** [macrozheng/mall#453]
![屏幕截图 2021-01-27 142308](https://user-images.githubusercontent.com/30338551/105951827-fb82d500-60b3-11eb-9ada-8512ce8e3b9d.png)
后台管理页面-权限-用户列表-分配角色
若不能分配多个角色，此处应有错误提示会比较好。

**Comment by macrozheng** [comment]
你使用的是演示环境吧，演示环境数据库是不允许更改的。
