### ISSUE TITLE
怎么排除mongdb ,消息队列的自动连接

### ISSUE THREAD

**Issue by chaolei-peng** [macrozheng/mall#456]
你好，在使用该项目，因为没有业务需要MongoDB和消息队列，不想他们运行后自动一直报错重连，有什么行之有效的方法能够解决这个问题，已经尝试过网上的排除，没有效果，很是疑问，期待您的答复，致谢！

**Comment by aaa7636602** [comment]
连接去掉就行了和...



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "PCL"<notifications@github.com&gt;; 
发送时间: 2021年2月2日(星期二) 下午5:24
收件人: "macrozheng/mall"<mall@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [macrozheng/mall] 怎么排除mongdb ,消息队列的自动连接 (#456)





 
你好，在使用该项目，因为没有业务需要MongoDB和消息队列，不想他们运行后自动一直报错重连，有什么行之有效的方法能够解决这个问题，已经尝试过网上的排除，没有效果，很是疑问，期待您的答复，致谢！
