### ISSUE TITLE
下单-库存校验不应该依赖前端传过来的库存数量

### ISSUE THREAD

**Issue by wangjia2016** [macrozheng/mall#457]
![image](https://user-images.githubusercontent.com/16084076/106838550-7dd45000-66d7-11eb-8e0d-960d28edd1f1.png)

hasStock

这样判断是有问题的，比如用户都停留在前端页面，这时候前端传的库存数都是一样的，

**Comment by macrozheng** [comment]
仔细看下`cartPromotionItem.setRealStock()`方法的调用可以发现，库存是从数据库中查询后设置进来的，最终查询方法为`portalProductDao.getPromotionProductList()`。
