### ISSUE TITLE
FK constraint 

### ISSUE THREAD

**Issue by xied75** [macrozheng/mall#458]
在阅读这里的时候http://www.macrozheng.com/#/database/mall_database_overview，
结构图里是有画Foreign Key的，但是使用这里的script：
https://github.com/macrozheng/mall/blob/master/document/sql/mall.sql
所创建的数据库里并没有任何的FK，这个是什么原因呢？

**Comment by aaa7636602** [comment]
作者手动关联的，建表sql并未显式指明哪些fk。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dong Xie"<notifications@github.com&gt;; 
发送时间: 2021年2月5日(星期五) 晚上11:34
收件人: "macrozheng/mall"<mall@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [macrozheng/mall] FK constraint  (#458)





 
在阅读这里的时候http://www.macrozheng.com/#/database/mall_database_overview，
 结构图里是有画Foreign Key的，但是使用这里的script：
 https://github.com/macrozheng/mall/blob/master/document/sql/mall.sql
 所创建的数据库里并没有任何的FK，这个是什么原因呢？

**Comment by xied75** [comment]
感谢回答，我是想问原作者不建立FK是因为这样做技术上更优么？没有FK的系统他是如何保证数据一致性的？

**Comment by xied75** [comment]
提这个问题是因为我本人既是程序猿也是DBA，看到这里这种风格我以为是业界的新潮流，所以忐忑的问一下希望得到点拨，后来搜了一下，比如这里https://dba.stackexchange.com/questions/168590/not-using-foreign-key-constraints-in-real-practice-is-it-ok

尤其令人感兴趣的这几句话：

> UPDATE: It seems it is a quite common approach for South Korean companies. I asked a few other seniors who worked for other companies, and most of them are saying they all doing like this. And even one of them worked for a financial company! Interesting...

> AFAIK alibaba in China has house rule that forbids the usage of foreign keys. Many others do the same.

看来这是阿里为人类做的又一伟大贡献了

>

**Comment by aaa7636602** [comment]
阿里禁用外键？为啥


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "macrozheng/mall"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月8日(星期一) 晚上9:04
收件人:&nbsp;"macrozheng/mall"<mall@noreply.github.com&gt;;
抄送:&nbsp;"黄太浩"<54639009@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [macrozheng/mall] FK constraint  (#458)





 
提这个问题是因为我本人既是程序猿也是DBA，看到这里这种风格我以为是业界的新潮流，所以忐忑的问一下希望得到点拨，后来搜了一下，比如这里https://dba.stackexchange.com/questions/168590/not-using-foreign-key-constraints-in-real-practice-is-it-ok
 
尤其令人感兴趣的这几句话：
  
UPDATE: It seems it is a quite common approach for South Korean companies. I asked a few other seniors who worked for other companies, and most of them are saying they all doing like this. And even one of them worked for a financial company! Interesting...
   
AFAIK alibaba in China has house rule that forbids the usage of foreign keys. Many others do the same.
  
看来这是阿里为人类做的又一伟大贡献了

**Comment by ewth126** [comment]
1.数据量大的情况下，外键性能太差了。（性能）
2.后续如果分库分表外键的处理要转成程序处理难度也很高。(扩展)
当然其他原因也很多。
如果是一个确定规模的项目，数据量增长各方面都很小，用外键是更方便更能保持数据一致性完整性的方案。
> 2021年2月7日 下午11:03，Dong Xie <notifications@github.com> 写道：
> 
> 这样
