### ISSUE TITLE
mall.ums_resource提供的数据库脚本没有

### ISSUE THREAD

**Issue by O-L-K** [macrozheng/mall#463]
***************

**Comment by O-L-K** [comment]
已

**Comment by aaa7636602** [comment]
有的。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "macrozheng/mall"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月11日(星期四) 上午10:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[macrozheng/mall] mall.ums_resource提供的数据库脚本没有 (#463)





 
提供的数据库脚本没有mall.ums_resource这张表嘛？怎么启动的时候找不到这张表
