### ISSUE TITLE
日志处理中，IP地址的设定

### ISSUE THREAD

**Issue by David-force** [macrozheng/mall#464]
**对象文件：**
com.macro.mall.common.log·WebLogAspect

**位置：**
73·行左右

**内容：**
`webLog.setIp(request.getRemoteUser());`
把用户信息设置到了IP地址里面

**Comment by aaa7636602** [comment]
应该是request.getRemoteAddr()




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "macrozheng/mall"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月14日(星期天) 下午4:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[macrozheng/mall] 日志处理中，IP地址的设定 (#464)





 
对象文件：
 com.macro.mall.common.log·WebLogAspect
 
位置：
 73·行左右
 
内容：
 webLog.setIp(request.getRemoteUser());
 把用户信息设置到了IP地址里面

**Comment by macrozheng** [comment]
确实有这个问题，已修复。
