### ISSUE TITLE
Is there any customer center in your admin backend service?

### ISSUE THREAD

**Issue by qyhdt** [macrozheng/mall#466]
Hey there, I am just wondering is there any customer center in your admin backend service, cause I haven't seen any menu related it.
![image](https://user-images.githubusercontent.com/7843730/113576116-8d2d3680-9651-11eb-818d-e78e7292e26e.png)

**Comment by aaa7636602** [comment]
what do you mean？

**Comment by yuchu2016** [comment]
well,he hasn't did it……

**Comment by yuchu2016** [comment]
well,he hasn't done it...
