### ISSUE TITLE
SecurityConfig类缺少@Configuration

### ISSUE THREAD

**Issue by ukong** [macrozheng/mall#467]

**Comment by aaa7636602** [comment]
1


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "macrozheng/mall"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 上午9:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[macrozheng/mall] SecurityConfig类缺少@Configuration (#467)

**Comment by aaa7636602** [comment]
不能加吧，加了会有问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "macrozheng/mall"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 上午9:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[macrozheng/mall] SecurityConfig类缺少@Configuration (#467)

**Comment by Juminiy** [comment]
SecurityConfig不是具体的配置类，只是一个抽象而已，最上层的配置类是mall-admin模块的MallSecurityConfig，

**Comment by devinlee24** [comment]
MallSecurityConfig才是配置类，SecurityConfig是抽象出来的
