### ISSUE TITLE
老大，后端项目直接用端口访问会不会有问题？

### ISSUE THREAD

**Issue by xlkit456852** [macrozheng/mall#468]
看到各个服务都启动了不同端口，那么前端直接调用后端的端口进行访问，这样会不会有问题？生产上会这样做吗？还是说可以做一个统一的入口？

**Comment by aaa7636602** [comment]
这个没有网关的

**Comment by macrozheng** [comment]
可以通过Nginx反向代理下，然后通过域名进行访问。
