### ISSUE TITLE
有拼团功能吗?

### ISSUE THREAD

**Issue by shi1234ww** [macrozheng/mall#477]
大神咱们项目有拼团功能吗? 支持订单分为多个包裹配送吗?

**Comment by aaa7636602** [comment]
木有拼团，订单多个商品会作为一个包裹。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月13日(星期四) 下午5:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [macrozheng/mall] 有拼团功能吗? (#477)





 
大神咱们项目有拼团功能吗? 支持订单分为多个包裹配送吗?
