### ISSUE TITLE
支付信息存到哪里了？

### ISSUE THREAD

**Issue by 0andy** [macrozheng/mall#478]
没看到数据库有支付记录表？
请问，支付信息存到哪里了？

谢谢

**Comment by aaa7636602** [comment]
订单表...



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月14日(星期五) 凌晨0:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [macrozheng/mall] 支付信息存到哪里了？ (#478)





 
没看到数据库有支付记录表？
 请问，支付信息存到哪里了？
 
谢谢
