### ISSUE TITLE
com.macro.mall.portal.controller.PmsPortalProductController#search接口的selectByExample查询不正确

### ISSUE THREAD

**Issue by sxc-one** [macrozheng/mall#480]
正常返回结果的查询如com.macro.mall.controller.PmsProductController#getList(com.macro.mall.dto.PmsProductQueryParam, java.lang.Integer, java.lang.Integer)的sql日志有如下两部分
![image](https://user-images.githubusercontent.com/61128128/118599032-86154e80-b7e1-11eb-824e-ebb7f6d8c4d6.png)，
而search接口只有selectByExample_COUNT一部分，导致返回的list为空
![image](https://user-images.githubusercontent.com/61128128/118599424-1358a300-b7e2-11eb-8f32-926203af0835.png)
请大佬指点一下是为什么呢？

**Comment by sxc-one** [comment]
查出来的数据条数“total”都是对的，就是list没数据

**Comment by macrozheng** [comment]
搜索接口查询的是Elasticsearch，不会打印SQL语句的。
