### ISSUE TITLE
商品es搜索问题

### ISSUE THREAD

**Issue by wang-c** [macrozheng/mall#481]
看了es搜索商品的相关代码，作者的demo太简单，就是个单表product同步入es,然后从es搜索也是product单维度字段搜索返回
这个场景太简单了，
假如有通过商品属性模糊搜索商品的需求，数据库模型是商品与商品属性是一对多的关系
通过属性模糊搜索出商品，需要分页排序等，该怎么做，

**Comment by macrozheng** [comment]
由于商品属性已经存在了`EsProduct`的`attrValueList`属性中，直接通过Elasticsearch的嵌套查询就可以实现了。
