### ISSUE TITLE
仅仅启动mall-admin登录出现的问题

### ISSUE THREAD

**Issue by gaoleng-cao** [macrozheng/mall#482]
只启动mall-admin登录的时候弹框出现“你已被登出，可以取消继续留在该页面，或者重新登录”怎么回事，控制台显示c.m.m.s.component.DynamicSecurityFilter  : Public object - authentication not attempted

**Comment by macrozheng** [comment]
可以参考下这篇文章[搞定Mall项目中的权限管理功能，弄懂这些问题就妥了！](https://mp.weixin.qq.com/s/AKbb9h3-g3h9m1ko9ulH2Q)

**Comment by sthwhl** [comment]
> 只启动mall-admin登录的时候弹框出现“你已被登出，可以取消继续留在该页面，或者重新登录”怎么回事，控制台显示c.m.m.s.component.DynamicSecurityFilter : Public object - authentication not attempted

最后解决了吗？

**Comment by xleixz** [comment]
这是一条自动回复的邮件。
 
您好，你发给我的信件已经收到！

**Comment by lei-hx** [comment]
这是一条自动回复的邮件。
 
您好，你发给我的信件已经收到！
