### ISSUE TITLE
支持多租户嘛？

### ISSUE THREAD

**Issue by zhuqiyun** [macrozheng/mall#485]

**Comment by aaa7636602** [comment]
支持多P



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月31日(星期一) 中午1:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [macrozheng/mall] 支持多租户嘛？ (#485)

**Comment by macrozheng** [comment]
暂时不支持
