### ISSUE TITLE
日志切面类表达式无法识别包

### ISSUE THREAD

**Issue by EricPeng1027** [macrozheng/mall#488]
切面类在common模块下，execution表达式无法匹配其他模块下的controller包，导致接口被调用时无法进入切面打印日志

**Comment by aaa7636602** [comment]
其他模块不都引用了conmmon模块吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月2日(星期三) 中午11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [macrozheng/mall] 日志切面类表达式无法识别包 (#488)





 
切面类在common模块下，execution表达式无法匹配其他模块下的controller包，导致接口被调用时无法进入切面打印日志

**Comment by EricPeng1027** [comment]
> 其他模块不都引用了conmmon模块吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年6月2日(星期三) 中午11:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [macrozheng/mall] 日志切面类表达式无法识别包 (#488) 切面类在common模块下，execution表达式无法匹配其他模块下的controller包，导致接口被调用时无法进入切面打印日志 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

其他模块是引用了common，现在问题是common识别不了其他模块下的包（common没有引用其他模块）
