### ISSUE TITLE
关于消息队列的一个问题请教一下

### ISSUE THREAD

**Issue by shicanLeft** [macrozheng/mall#50]
我在代码中(CancelOrderSender.sendMessage)看到将消息发送给队列(mall.order.cancel.ttl);
但是在接受代码中(CancelOrderReceiver#16行)又是监听的@RabbitListener(queues = "mall.order.cancel")队列，这里发送消息的队列是不是应该也写成mall.order.cancel而不是mall.order.cancel.ttl

**Comment by macrozheng** [comment]
这是一个实现延迟任务的场景，消息设置了超期时间，一旦消息到期会自动从mall.order.cancel.ttl转发到mall.order.cancel

**Comment by shicanLeft** [comment]
那请问一下 ：消息设置了超时时间，超时自动转到mall.order.cancle  这部分是在代码里面实现的吗？能不能告诉我代码的位置？

**Comment by macrozheng** [comment]
在该文件的：https://github.com/macrozheng/mall/blob/master/mall-portal/src/main/java/com/macro/mall/portal/config/RabbitMqConfig.java
orderTtlQueue（）方法中。
