### ISSUE TITLE
关于全局异常捕获

### ISSUE THREAD

**Issue by yanwencheng** [macrozheng/mall#502]
咱们微服务项目做全局异常捕获处理了么，碰到了自定义全局异常再被其他服务调用时直接触发服务降级，如果把HttpStatus调整为200异常无法抛出

**Comment by Nashmi97** [comment]
> 咱们微服务项目做全局异常捕获处理了么，碰到了自定义全局异常再被其他服务调用时直接触发服务降级，如果把HttpStatus调整为200异常无法抛出
