### ISSUE TITLE
security认证为什么在登录接口setAuthentication成功了，还需要在自定义类JwtAuthenticationTokenFilter重新setAuthentication，只在登录接口setAuthentication而已获取到的主体为空。这是为何？

### ISSUE THREAD

**Issue by huanglf1024** [macrozheng/mall#503]
is:issue is:open security认证为什么在登录接口setAuthentication成功了，还需要在自定义类JwtAuthenticationTokenFilter重新setAuthentication，只在登录接口setAuthentication而已获取到的主体为空。这是为何？

**Comment by Laiyu777** [comment]
@huanglf1024 因为sessionManagement 设置了不生成的策略，这样一来，请求就都是独立的了，每次都会重新判断，之所以每次都 setAuthentication 一下，是为了之后的鉴权操作，要先 setAuthentication，才可以进行鉴权
