### ISSUE TITLE
前端项目mall-app-web项目什么时候能上线啊，已经期待很久了

### ISSUE THREAD

**Issue by David20160511** [macrozheng/mall#505]
前端项目mall-app-web项目什么时候能上线啊，已经期待很久了

**Comment by Godover** [comment]
哈哈，巧了，还真能改，Android转后端

**Comment by aaa7636602** [comment]
为啥转呀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: GodOver ***@***.***&gt;
发送时间: 2022年4月3日 00:45
收件人: macrozheng/mall ***@***.***&gt;
抄送: huangdada ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [macrozheng/mall] 前端项目mall-app-web项目什么时候能上线啊，已经期待很久了 (#505)





 
哈哈，巧了，还真能改，Android转后端

**Comment by Godover** [comment]
> 为啥转呀 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: GodOver ***@***.***&gt; 发送时间: 2022年4月3日 00:45 收件人: macrozheng/mall ***@***.***&gt; 抄送: huangdada ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [macrozheng/mall] 前端项目mall-app-web项目什么时候能上线啊，已经期待很久了 (#505) 哈哈，巧了，还真能改，Android转后端 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;



> 为啥转呀 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: GodOver ***@***.***&gt; 发送时间: 2022年4月3日 00:45 收件人: macrozheng/mall ***@***.***&gt; 抄送: huangdada ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [macrozheng/mall] 前端项目mall-app-web项目什么时候能上线啊，已经期待很久了 (#505) 哈哈，巧了，还真能改，Android转后端 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Android没啥意思，厌烦和客户端交互了

**Comment by albertliutec** [comment]
同问

**Comment by aboutZZ** [comment]
别期待了，作者一直在刷假提交（看了提交记录，提交的代码全是不痛不痒），刷活跃度，实质上这项目两年没更新了

**Comment by euphoria429** [comment]
> 别期待了，作者一直在刷假提交（看了提交记录，提交的代码全是不痛不痒），刷活跃度，实质上这项目两年没更新了

我等了一年了^ ^哈哈，毕竟作者也有自己的生活吧x

**Comment by macrozheng** [comment]
已经开源了，项目地址：https://github.com/macrozheng/mall-app-web

**Comment by aboutZZ** [comment]
![图片](https://github.com/macrozheng/mall/assets/15063761/140e4a9c-bfbb-49fe-a505-c02d3587bff3)

删老子评论？怎么，后端你就是在刷提交，刷活跃，还不让人说了？心虚了这是
