### ISSUE TITLE
大四菜鸟求指导

### ISSUE THREAD

**Issue by LazyB0705** [macrozheng/mall#507]
我克隆下来代码之后启动也可能算是正常 但是打开8080之后显示 401暂未登录或token已过期 学完Springboot第一次接触项目很们懵
![image](https://user-images.githubusercontent.com/92066481/138688021-f74ae83d-c0e0-4e8a-9598-ae0fd4a5de91.png)

**Comment by wuliyi** [comment]
> 我克隆下来代码之后启动也可能算是正常 但是打开8080之后显示 401暂未登录或token已过期 学完Springboot第一次接触项目很们懵 ![image](https://user-images.githubusercontent.com/92066481/138688021-f74ae83d-c0e0-4e8a-9598-ae0fd4a5de91.png)

页面提示了，你没有登录。需要先注册或用账户和密码登录(可以用root/root，更多内容请查看数据库的[ums_admin表])，然后记录下返回的Token。在之后的请求中加上请求头【Authorization : Bearer token】。具体服务地址请查看项目的Controller层@RequestMapping注解。 -- 可自行实现前端代码或使用postman(教程：http://www.macrozheng.com/#/reference/postman)
![image](https://user-images.githubusercontent.com/37173098/140717550-c1ab6310-76ed-45c0-8b7d-b2093078d23a.png)
