### ISSUE TITLE
MailSearchApplication run error

### ISSUE THREAD

**Issue by zifeichen** [macrozheng/mall#51]
org.elasticsearch.transport.NodeDisconnectedException: [][127.0.0.1:9300][cluster:monitor/nodes/liveness] disconnected

2019-02-26 19:17:30.537  INFO 39380 --- [][generic][T#1]] org.elasticsearch.client.transport       : [Maria Hill] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9300}, disconnecting...

**Comment by zifeichen** [comment]
version 6.6.1

**Comment by zifeichen** [comment]
127.0.0.1:9200 .      127.0.0.1:9100 都能连接成功

**Comment by macrozheng** [comment]
把elasticsearch版本改成2.4.6，springboot 1.5.x和elasticsearch6.x版本有兼容性问题

**Comment by zifeichen** [comment]
昨晚elasticsearch启动日志发现这个问题，更换版本解决了，感谢🙏

**Comment by zifeichen** [comment]
你好，我想问一下mybatis generator 是orm框架吗？  就是您写的这个mall-mbg工程。 求教
