### ISSUE TITLE
请问一下，为什么我启动时提示缺少ums_resources表

### ISSUE THREAD

**Issue by LYQBOY** [macrozheng/mall#515]
运行的项目是mall_admin。
数据库文件我下载好了，执行sql文件后产生了71个表，但是没有ums_resrouces表呀。
求助！！！

**Comment by aaa7636602** [comment]
应该是72张表



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CZFLNCX ***@***.***&gt;
发送时间: 2021年12月3日 15:21
收件人: macrozheng/mall ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [macrozheng/mall] 请问一下，为什么我启动时提示缺少ums_resources表 (Issue #515)

**Comment by LYQBOY** [comment]
> 应该是72张表 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: CZFLNCX ***@***.***&gt; 发送时间: 2021年12月3日 15:21 收件人: macrozheng/mall ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [macrozheng/mall] 请问一下，为什么我启动时提示缺少ums_resources表 (Issue #515)

**Comment by LYQBOY** [comment]
感谢，我刚刚从document文件夹里下载了完整的sql文件
