### ISSUE TITLE
mall-gateway为什么用WebFlux呢，有什么意义吗？

### ISSUE THREAD

**Issue by Fr3027** [macrozheng/mall#522]

**Comment by aaa7636602** [comment]
强行用吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Fr3027 ***@***.***&gt;
发送时间: 2022年1月14日 09:57
收件人: macrozheng/mall ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [macrozheng/mall] mall-gateway为什么用WebFlux呢，有什么意义吗？ (Issue #522)

**Comment by Fr3027** [comment]
我也有这种感觉，而且现有的权限控制有问题

**Comment by aboutZZ** [comment]
gateway是流量入口，使用webflux非阻塞式编程能撑起高并发，用传统MVC阻塞式编程网关要挂。
PS：`Spring cloud gateway` 本身就是用的`webflux`
