### ISSUE TITLE
登陆的时候提示暂未登录或者token已过期怎么回事

### ISSUE THREAD

**Issue by 17663081373** [macrozheng/mall#533]

**Comment by cchgenius** [comment]
我也是这样，401错误
![image](https://user-images.githubusercontent.com/39299930/164364751-740464c7-f31f-4393-9bd7-fd344225a226.png)

**Comment by sthwhl** [comment]
解决了吗？一样的问题

**Comment by cchgenius** [comment]
> 解决了吗？一样的问题

调用/admin/login，到数据库中查看用户名密码，参数是username和password，调用成功会返回token，把token填入你要调用的接口就行了
