### ISSUE TITLE
用admin的token登陆后常规接口提示403

### ISSUE THREAD

**Issue by bzwwrd** [macrozheng/mall#534]
大佬，请问我用token登陆后访问正常接口提示我403没有权限是为什么呀
<img width="351" alt="image" src="https://user-images.githubusercontent.com/55166608/159157819-dd9eadbe-8ff0-4e63-b3d7-9b57b3612e3b.png">
删掉@PreAuthorize("hasAuthority('pms:brand:read')")后可以正常返回

**Comment by aaa7636602** [comment]
应该不会吧，带了token还403



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yuning Song ***@***.***&gt;
发送时间: 2022年3月20日 18:21
收件人: macrozheng/mall ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [macrozheng/mall] 用admin的token登陆后常规接口提示403 (Issue #534)

**Comment by bzwwrd** [comment]
> 应该不会吧，带了token还403 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Yuning Song ***@***.***&gt; 发送时间: 2022年3月20日 18:21 收件人: macrozheng/mall ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [macrozheng/mall] 用admin的token登陆后常规接口提示403 (Issue #534)

看后台确实认证成功了，但是swagger这里还是403
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/55166608/159159901-279825b8-a8c6-4951-af33-f012721d7fc3.png">

**Comment by aaa7636602** [comment]
你swsgger没加token呗


------------------ 原始邮件 ------------------
发件人: Yuning Song ***@***.***&gt;
发送时间: 2022年3月20日 19:24
收件人: macrozheng/mall ***@***.***&gt;
抄送: huangdada ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [macrozheng/mall] 用admin的token登陆后常规接口提示403 (Issue #534)

**Comment by bzwwrd** [comment]
> 你swsgger没加token呗
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Yuning Song ***@***.***&gt; 发送时间: 2022年3月20日 19:24 收件人: macrozheng/mall ***@***.***&gt; 抄送: huangdada ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [macrozheng/mall] 用admin的token登陆后常规接口提示403 (Issue #534)

加了
<img width="541" alt="image" src="https://user-images.githubusercontent.com/55166608/159168430-3c2f75f1-fda5-4a3f-b24d-b9e3d4d5543d.png">

**Comment by wangfachang111** [comment]
你发错邮箱了，找错人了



---原始邮件---
发件人: "Yuning ***@***.***&gt;
发送时间: 2022年3月20日(周日) 晚上10:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [macrozheng/mall] 用admin的token登陆后常规接口提示403 (Issue #534)




  
你swsgger没加token呗
 …
 ------------------ 原始邮件 ------------------ 发件人: Yuning Song @.&gt; 发送时间: 2022年3月20日 19:24 收件人: macrozheng/mall @.&gt; 抄送: huangdada @.&gt;, Comment @.&gt; 主题: Re: [macrozheng/mall] 用admin的token登陆后常规接口提示403 (Issue #534)
  
加了
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aaa7636602** [comment]
你swsgger没加token呗


------------------ 原始邮件 ------------------
发件人: Yuning Song ***@***.***&gt;
发送时间: 2022年3月20日 19:24
收件人: macrozheng/mall ***@***.***&gt;
抄送: huangdada ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [macrozheng/mall] 用admin的token登陆后常规接口提示403 (Issue #534)





------------------ 原始邮件 ------------------
发件人: Yuning Song ***@***.***&gt;
发送时间: 2022年3月20日 19:24
收件人: macrozheng/mall ***@***.***&gt;
抄送: huangdada ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [macrozheng/mall] 用admin的token登陆后常规接口提示403 (Issue #534)






应该不会吧，带了token还403 发自我的iPhone
…
------------------ 原始邮件 ------------------ 发件人: Yuning Song @.&gt; 发送时间: 2022年3月20日 18:21 收件人: macrozheng/mall @.&gt; 抄送: Subscribed @.***&gt; 主题: Re: [macrozheng/mall] 用admin的token登陆后常规接口提示403 (Issue #534)

看后台确实认证成功了，但是swagger这里还是403


&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aaa7636602** [comment]
那是什么鬼哦？不应该啊
------------------ 原始邮件 ------------------
发件人: Yuning Song ***@***.***&gt;
发送时间: 2022年3月20日 22:54
收件人: macrozheng/mall ***@***.***&gt;
抄送: huangdada ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [macrozheng/mall] 用admin的token登陆后常规接口提示403 (Issue #534)






你swsgger没加token呗
…
------------------ 原始邮件 ------------------ 发件人: Yuning Song @.&gt; 发送时间: 2022年3月20日 19:24 收件人: macrozheng/mall @.&gt; 抄送: huangdada @.&gt;, Comment @.&gt; 主题: Re: [macrozheng/mall] 用admin的token登陆后常规接口提示403 (Issue #534)

加了


—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bzwwrd** [comment]
找到原因了，我用的是mall-learning项目的代码，但是sql文件用的是mall项目的，权限管理逻辑不一样了，太蠢了。。给大佬添麻烦了orz

**Comment by kairenxue** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
