### ISSUE TITLE
能否把商城端代码分享出来

### ISSUE THREAD

**Issue by zhang145926** [macrozheng/mall#536]
能否把商城端代码分享出来

**Comment by sunfei7777** [comment]
您好，这里是孙鹏飞。
您发送的邮件已经收到。

**Comment by kairenxue** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by liaock** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yufeng007** [comment]
这是一封自动回复邮件。
 
你好，来信已收到。感谢你的来信，阅后会尽快回复。

**Comment by yufeng007** [comment]
这是一封自动回复邮件。
 
你好，来信已收到。感谢你的来信，阅后会尽快回复。
