### ISSUE TITLE
下载不到这个镜像mall/mall-admin:1.0-SNAPSHOT

### ISSUE THREAD

**Issue by Er1c0** [macrozheng/mall#538]
mall在Linux环境下的部署（基于Docker Compose） | mall学习教程
https://www.macrozheng.com/mall/deploy/mall_deploy_docker_compose.html#%E5%AF%B9%E4%BE%9D%E8%B5%96%E6%9C%8D%E5%8A%A1%E8%BF%9B%E8%A1%8C%E4%BB%A5%E4%B8%8B%E8%AE%BE%E7%BD%AE

**Comment by macrozheng** [comment]
这个镜像需要自行打包，具体参考[使用Maven插件为SpringBoot应用构建Docker镜像](https://www.macrozheng.com/mall/reference/docker_maven.html) 。

**Comment by Drun1baby** [comment]
这样太麻烦了。。。。emmmm

**Comment by WinJayX** [comment]
> 这样太麻烦了。。。。emmmm

这不是麻烦，是需要收费的。。。
