### ISSUE TITLE
什么辣鸡项目 满大街都是你的地址 让进去点 star  

### ISSUE THREAD

**Issue by wajncn** [macrozheng/mall#544]
# 什么辣鸡项目 满大街都是你的地址 让进去点 star

**Comment by wajncn** [comment]
哪个优秀的项目会满大街的让人给点star ？   走过路过还千万不要错过呀

**Comment by ASMSG** [comment]
wajncn ***@***.***>于2022年5月26日 周四上午8:31写道：

**Comment by Tayoou** [comment]
这也能喷啊，别人加地址和别人项目怎么样有什么关系

**Comment by wajncn** [comment]
挂猪头卖牛肉不能喷？
在 2022年5月26日 +0800 08:40，Tayoou ***@***.***>，写道：
