### ISSUE TITLE
请问maintainer在干嘛？commit history一团糟

### ISSUE THREAD

**Issue by VoidxHoshi** [macrozheng/mall#546]
每隔几天随便改点删点，就乱commit一次，水commit吗？刷虚假的repo活跃度？

**Comment by 80boys** [comment]
开源项目,爱用不用,可以虚心提建议,但请收回你的傲慢

**Comment by aboutZZ** [comment]
我也提了这个issue，指出他大量虚假提交，然后没一句回应，直接被删了，原来感觉作者挺不错，现在感觉真恶心😓

往前翻了翻，2020年3月后这项目就没更新了，两年多了，全是虚假提交刷活跃度
