### ISSUE TITLE
请问为什么不用mybatis-plus

### ISSUE THREAD

**Issue by zhaolei1206** [macrozheng/mall#549]
请问大佬，为什么不选用mybatis-plus框架，是因为已选用mybatis后改造工作量大还是，mybatis-plus本身的什么问题，望解答

**Comment by moumoukings** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    问就是东西都给你了，想怎么改造自己玩
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                zhangzichen6210
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年06月23日 11:52
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [macrozheng/mall] 请问为什么不用mybatis-plus (Issue #549)
        
      
    
  
  

请问大佬，为什么不选用mybatis-plus框架，是因为已选用mybatis后改造工作量大还是，mybatis-plus本身的什么问题，望解答



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
