### ISSUE TITLE
登录不上 admin-mall-web，输入密码后，点击登录页面报 404 

### ISSUE THREAD

**Issue by sthwhl** [macrozheng/mall#550]
使用 windows 部署，登录界面报： Request failed with status code 404
看后台 admin-mall 报：c.m.m.s.component.DynamicSecurityFilter  : Public object - authentication not attempted

**Comment by sthwhl** [comment]
解决了

**Comment by lookcompany** [comment]
密码是多少，在哪里找的？

**Comment by xp5313** [comment]
你好，想问下部署完之后密码是多少？？？
