### ISSUE TITLE
安全漏洞 / security vulnerability

### ISSUE THREAD

**Issue by michaellrowley** [macrozheng/mall#555]
您好，在研究开源代码时，我在此存储库中发现了一个安全漏洞。

我在 4 月份通过一个名为“huntr”的网站报告了该漏洞，但他们打开了一个不久后关闭的报告——我想用中文打开另一个报告，以便您正确理解该问题。

[您可以在此处查看报告。](https://huntr.dev/bounties/b3614dc3-651d-46c4-8519-118d06e26771/)
[您可以在此处查看打开的初始问题。](https://github.com/macrozheng/mall/issues/535)

谢谢你。

~ via Google Translate

-----------------------

Hello, while researching open-source code I found a security vulnerability in this repository.

I reported the vulnerability via a website called 'huntr' in April but they opened a report which was closed shortly after - I wanted to open another in Chinese so that you can properly understand the issue.

[You can view the report here.](https://huntr.dev/bounties/b3614dc3-651d-46c4-8519-118d06e26771/)
[You can view the initial issue that was opened here.](https://github.com/macrozheng/mall/issues/535)

Thank you.

**Comment by aboutZZ** [comment]
Haha, the author care about shit on this.

**Comment by sunfei7777** [comment]
您好，这里是孙鹏飞。
您发送的邮件已经收到。

**Comment by liaock** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
