### ISSUE TITLE
菜鸟求助：java:8镜像已失效，package出错

### ISSUE THREAD

**Issue by kanesp** [macrozheng/mall#570]
java:8镜像已失效，package出错`{"message":"manifest for java:8 not found: manifest unknown: manifest unknown"} (Not Found: 404)`，能否直接使用openjdk的8镜像？
谢谢大佬！:)

**Comment by PandaGu** [comment]
使用openjdk:8已成功部署。改吧

**Comment by kanesp** [comment]
嗯，当天已经部署好了，用的openjdk:8
