### ISSUE TITLE
ums_permission 代码里用了吗

### ISSUE THREAD

**Issue by tyleryu12** [macrozheng/mall#574]

**Comment by Adela123456** [comment]
最新发布的授权里,用了动态路径规划的没有用到,用的是ums_resource这个表

**Comment by yubingkun** [comment]
ums_permission 那这个后续准备怎么用有思路吗？

**Comment by Adela123456** [comment]
他这个后面就没用了，用的是ums_resource这个表。
之前用过的，是在给出的小例子利用到的ums_permission这个表




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "macrozheng/mall"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月3日(星期四) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [macrozheng/mall] ums_permission 代码里用了吗 (Issue #574)





 
ums_permission 那这个后续准备怎么用有思路吗？
