### ISSUE TITLE
mybatis查询问题

### ISSUE THREAD

**Issue by Zmz-020716** [macrozheng/mall#577]
PmsProductDao 的 getUpdateInfo() 返回值是一个实体类 PmsProductResult，但实际查询时会查询出多条记录（对应 list），此时为什么不会报错？
![image](https://user-images.githubusercontent.com/71144052/205445223-a6e75c5d-d57d-421d-8a4f-84f80be745ce.png)
![image](https://user-images.githubusercontent.com/71144052/205445268-2b67534b-49c8-46eb-ace0-433fa582f0c4.png)

**Comment by lht1936** [comment]
你的数据是错的，id是自增的，不会重复。

**Comment by Zmz-020716** [comment]
> 你的数据是错的，id是自增的，不会重复。

这是 mybatis 执行的sql日志，跟数据库软件的结果一样
![image](https://user-images.githubusercontent.com/71144052/205843022-4dcc6f41-ab00-476f-8c71-f51916f6ee43.png)
