### ISSUE TITLE
这块为什么不直接从configAttributeMap中取key为path的value,若value不为空则添加到configAttributes中，而是遍历比较呢?

### ISSUE THREAD

**Issue by zqf425** [macrozheng/mall#586]
https://github.com/macrozheng/mall/blob/81ff4e32d1900c1d35a9511a02f93457461d8c3c/mall-security/src/main/java/com/macro/mall/security/component/DynamicSecurityMetadataSource.java#L44

**Comment by it985** [comment]
作者一直在刷假提交（看了提交记录，提交的代码全是不痛不痒），刷活跃度，实质上这项目两年没更新了

**Comment by glp800** [comment]
我也不知道啊，脑壳大

**Comment by t1kcode** [comment]
因为是ANT模式的路径，有通配符。
![Snipaste_2023-03-18_22-30-54](https://user-images.githubusercontent.com/58599955/226112379-719f7a81-f882-4dd0-9f05-e9a061ff4fc2.jpg)
