### ISSUE TITLE
springsecurity权限校验存在问题

### ISSUE THREAD

**Issue by shenbingyu** [macrozheng/mall#587]
在开启debug日志的时候就会发现任何请求super.beforeInvocation(fi)这个方法都会执行两次，导致执行请求一次会打两份日志，配置逻辑存在问题
![image](https://user-images.githubusercontent.com/37618101/212551232-c05b922d-39ab-4543-b937-dd984d7e74cd.png)
具体位置在这里，也就是说一次请求会进行两次权限校验。
![image](https://user-images.githubusercontent.com/37618101/212551655-12bcc990-e4d7-4fa5-8ab2-525db4286610.png)

**Comment by zpj80231** [comment]
是的，我也发现了这个问题

**Comment by Maakkong** [comment]
应该是动态权限的filter被spring自动注册的时候加入了系统调用链，后面又手动加入了一次调用链导致的

**Comment by liumingsongning** [comment]
怎么感觉加了权限验证好慢，简单返回个字符串都得5，6秒
