### ISSUE TITLE
关于docker-compose-env在nginx 容器配置的问题

### ISSUE THREAD

**Issue by zwssunny** [macrozheng/mall#593]
在nginx 容器部分的volumes的#配置文件目录挂载中/mydata/nginx/conf:/etc/nginx 这样启动后会报错，找不到/etc/nginx/mime.types文件，原因是这样设置将屏蔽了容器内的目录/etc/nginx/，应该设成单独的配置文件映射/mydata/nginx/conf/nginx.conf:/etc/nginx/nginx.conf

**Comment by macrozheng** [comment]
可以先运行一次容器，再使用`docker container cp nginx:/etc/nginx /mydata/nginx/`从容器中拷贝文件出来，具体参考[mall在Linux环境下的部署（基于Docker容器）](https://www.macrozheng.com/mall/deploy/mall_deploy_docker.html#nginx%E5%AE%89%E8%A3%85)。
