### ISSUE TITLE
ums_role_permission_relation表中没有role_id为5的

### ISSUE THREAD

**Issue by t1kcode** [macrozheng/mall#594]
![image](https://user-images.githubusercontent.com/58599955/222087407-35903560-08f1-4269-bb26-cdc7a924c4b2.png)

**Comment by macrozheng** [comment]
该表已经弃用了，权限逻辑及相关表具体可以参考[《手把手教你搞定权限管理，结合Spring Security实现接口的动态权限控制！》](https://www.macrozheng.com/mall/technology/permission_back.html)。
