### ISSUE TITLE
商品属性分类管理和商品属性管理的url是一样的，有什么区别吗？

### ISSUE THREAD

**Issue by t1kcode** [macrozheng/mall#595]
![image](https://user-images.githubusercontent.com/58599955/226113066-8a1018ad-fd7e-4c3b-946f-fd4c35ebb5fd.png)
实际上在这部分代码中
https://github.com/macrozheng/mall/blob/81ff4e32d1900c1d35a9511a02f93457461d8c3c/mall-security/src/main/java/com/macro/mall/security/component/DynamicSecurityMetadataSource.java#L36
在configAttributeMap中商品属性分类管理也会被商品属性管理覆盖掉。

**Comment by macrozheng** [comment]
`商品属性分类管理`对应的url应该设置为`​/productAttribute​/category​/**`，与接口地址对应。
