### ISSUE TITLE
关于按钮权限控制

### ISSUE THREAD

**Issue by 1248142645** [macrozheng/mall#597]
文档有介绍ums_permission表已经不再使用，但为什么不再使用，用什么方式替代实现按钮权限控制，mall里现在有实现吗

**Comment by sunfei7777** [comment]
您好，这里是孙鹏飞。
您发送的邮件已经收到。

**Comment by liaock** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by macrozheng** [comment]
按钮的点击，一般都会伴随接口的调用，可以通过分配接口资源来控制。
