### ISSUE TITLE
生成sku问题

### ISSUE THREAD

**Issue by ABBOOT** [macrozheng/mall#598]
场景复现：
1. 默认那几个我新增了一个属性->刷新列表->数据正常;
2. 删除新增的属性->刷新列表->提交->500

**Comment by ABBOOT** [comment]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/29647378/233845655-4d2599a5-11cd-409c-b5a3-27048f10794f.png">

**Comment by macrozheng** [comment]
演示环境数据只有只读权限，想要修改数据需要本地搭建后端服务。
