### ISSUE TITLE
Elasticsearch中索引pms的结构

### ISSUE THREAD

**Issue by single-ing** [macrozheng/mall#639]
pms的结构是如何的，麻烦告知一下；
有直接的创建语句更好

**Comment by sunfei7777** [comment]
您好，这里是孙鹏飞。
您发送的邮件已经收到。

**Comment by zkchen** [comment]
来信已收到。

**Comment by liaock** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by macrozheng** [comment]
es中的数据结构是自动创建的。
