### ISSUE TITLE
Error creating bean with name

### ISSUE THREAD

**Issue by noThinkingFish** [macrozheng/mall#643]
mall-search项目有扫描不到esProductRepository的问题，其他项目mall-portal则没有这个问题。Error creating bean with name 'esProductRepository' defined in com.macro.mall.search.repository.EsProductRepository defined in @EnableElasticsearchRepositories declared on ElasticsearchRepositoriesRegistrar.EnableElasticsearchRepositoriesConfiguration: Invocation of init method failed;

**Comment by macrozheng** [comment]
检查下使用的es版本是否为7.17.3版本
