### ISSUE TITLE
部署 Linux 版本下的 rabbitMQ 时报错，无法添加一个名为 mall/mall 的 admin 账户

### ISSUE THREAD

**Issue by Drun1baby** [macrozheng/mall#648]
报错如图，是 js 的问题

![image](https://github.com/macrozheng/mall/assets/75228348/697d0bcd-77c2-4f92-b8ba-7822a93d68b2)

**Comment by macrozheng** [comment]
Docker镜像版本问题，使用3.9.11-management版本的就可以了。
