### ISSUE TITLE
docker打包部署报错

### ISSUE THREAD

**Issue by kingtiger2** [macrozheng/mall#650]
Failed to execute goal io.fabric8:docker-maven-plugin:0.43.1:build (build-image) on project mall-admin: Execution build-image of goal io.fabric8:docker-maven-plugin:0.43.1:build failed: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive

升级了版本也不行

**Comment by sunfei7777** [comment]
您好，这里是孙鹏飞。
您发送的邮件已经收到。

**Comment by liaock** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
