### ISSUE TITLE
minio对象存储功能不完善-大佬后续会写吗？

### ISSUE THREAD

**Issue by ChangSZ** [macrozheng/mall#658]
看了下，前端把阿里云对象存储给关掉了，使用minio，但minio upload成功后返回了`http://localhost:9000/mall/20240520/xxx.png`的URL，这个URL无签名，会访问失败的。

是否要新增个接口，upload返回该新接口
- 方法1：新接口中进行预签名，前端获得该签名URL再直接访问
- 方法2：新接口中进行预签名，并直接访问minio将对象返回

**Comment by macrozheng** [comment]
存储桶的权限问题吧，把存储桶的权限改成可读就能访问了
