### ISSUE TITLE
环境部署是否可以增加 mac 环境使用 brew 部署

### ISSUE THREAD

**Issue by caosuyang** [macrozheng/mall#661]
环境部署是否可以增加 mac 环境使用 brew 部署，因为很大部分是通过 mac 进行 java 项目开发的，本地的项目配置需要使用 brew 工具。

**Comment by sunfei7777** [comment]
您好，这里是孙鹏飞。
您发送的邮件已经收到。

**Comment by liaock** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by macrozheng** [comment]
可以装个docker环境，在docker环境下部署项目
