### ISSUE TITLE
启动项目时报错： init datasource error

### ISSUE THREAD

**Issue by Alanzhang92** [macrozheng/mall#70]
环境搭配好以后，启动MallAdminApplication时报错：
[ost-startStop-1] com.alibaba.druid.pool.DruidDataSource   : init datasource error, url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8

**Comment by CNsmallC** [comment]
你检查下是否导入数据库,以及mysql账号密码对不对
