### ISSUE TITLE
docker-compose.yml 这种方式的安装失败

### ISSUE THREAD

**Issue by LianWilliam** [macrozheng/mall#77]
[root@localhost mall]# ll
总用量 2
-rw-r--r--. 1 root root 1370 3月  27 18:02 docker-compose.yml
[root@localhost mall]# docker-compose up -d
Pulling mall-admin (mall/mall-admin:0.0.1-SNAPSHOT)...
Trying to pull repository docker.io/mall/mall-admin ...
ERROR: repository docker.io/mall/mall-admin not found: does not exist or no pull access
[root@localhost mall]#

请问有没有谁做好了Docker的镜像文件呢，不胜感激。

**Comment by macrozheng** [comment]
需要自行搭建Docker Registry镜像仓库和构建镜像，可以参考下这个文档：https://github.com/macrozheng/mall/blob/master/document/reference/docker.md
