### ISSUE TITLE
search模块报错，需要修改es配置

### ISSUE THREAD

**Issue by hehuilei** [macrozheng/mall#79]
改动2点：
增加集群名字配置
cluster-name:xxx

修改通讯端口:
cluster-nodes: 127.0.0.1:9300
9300用户tcp通讯，9200用于http

**Comment by macrozheng** [comment]
你要是不修改项目中的cluster-name就可以直接使用，但你要是修改了项目中的cluster-name，你的es的配置文件中也要进行相应修改。
