### ISSUE TITLE
Missing artifact com.macro.mall:mall-mbg:jar:1.0-SNAPSHOT 

### ISSUE THREAD

**Issue by oscar-liu** [macrozheng/mall#80]
我启动的时候，pom.xml报这个报错，
Missing artifact com.macro.mall:mall-mbg:jar:1.0-SNAPSHOT

**Comment by oscar-liu** [comment]
错误: 找不到或无法加载主类 com.macro.mall.MallAdminApplication

**Comment by macrozheng** [comment]
你用的是Eclipse么，maven install mall-mbg到本地maven仓库

**Comment by Xiuyu1995** [comment]
我在用idea双击package进行构建的时候出现这个问题，请问该怎么解决呢？

**Comment by NingSmile** [comment]
idea 内双击 package 也出现了Could not find artifact com.macro.mall:mall-mbg:pom:1.0-SNAPSHOT...
