### ISSUE TITLE
mysql依赖问题

### ISSUE THREAD

**Issue by Blusez** [macrozheng/mall#81]
导入idea之后，mysql都依赖mbg的版本，但是demo等项目中依赖的确是8.0版本的mysql，而且我也没有找到彼得mysql依赖
![image](https://user-images.githubusercontent.com/13349444/55527136-502cb300-56ca-11e9-927d-2ac25a59541c.png)
![image](https://user-images.githubusercontent.com/13349444/55527176-718d9f00-56ca-11e9-9479-a041387307f2.png)

**Comment by macrozheng** [comment]
目前项目使用的是mysql8.0的驱动，mbg中的驱动也已经更正，可以看下最新代码。
