### ISSUE TITLE
不能启动mall-search

### ISSUE THREAD

**Issue by SurfingFish** [macrozheng/mall#83]
mall-search里面的配置没有改过，elasticsearch里面的cluster-name: my-application，运行时出现failed to load elasticsearch nodes : org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{-TFK3OcjRzyCYt-9ucivhg}{127.0.0.1}{127.0.0.1:9300}]

WARN 9948 --- [           main] o.e.c.t.TransportClientNodesService      : node {#transport#-1}{-TFK3OcjRzyCYt-9ucivhg}{127.0.0.1}{127.0.0.1:9300} not part of the cluster Cluster [elasticsearch], ignoring...

![image](https://user-images.githubusercontent.com/12906583/55713565-839d7380-5a23-11e9-9e8d-04bfb11ce7a6.png)
![image](https://user-images.githubusercontent.com/12906583/55713588-8c8e4500-5a23-11e9-84a2-2ba21c02afe1.png)
![image](https://user-images.githubusercontent.com/12906583/55713602-93b55300-5a23-11e9-8604-be1822d8bf1d.png)
![image](https://user-images.githubusercontent.com/12906583/55713659-ad569a80-5a23-11e9-97a7-295799cb8b6e.png)

**Comment by macrozheng** [comment]
把最后一张截图的cluster.name那行注释掉即可

**Comment by huang365** [comment]
我的一开始也是报你的这个错误，但是我加了这行指定名称：  cluster-name: elasticsearch   
就没有再报错了。

**Comment by SurfingFish** [comment]
我试一下，老铁
