### ISSUE TITLE
启动 mall-admin 报model&mapper不存在

### ISSUE THREAD

**Issue by chaojiangcn** [macrozheng/mall#89]
昨天拉的代码是，上传丢失了嘛？

**Comment by chaojiangcn** [comment]
只启动mall-admin  启动不起来

**Comment by chaojiangcn** [comment]
![image](https://user-images.githubusercontent.com/29300205/56225931-da025600-60a4-11e9-9ef5-f04ea8c43b9c.png)

**Comment by macrozheng** [comment]
你是mybatis依赖没下载下来吧

**Comment by chaojiangcn** [comment]
> 你是mybatis依赖没下载下来吧
多谢大佬。
嗯，我的插件先编译后安装的  报错了
