### ISSUE TITLE
跪求app端源码

### ISSUE THREAD

**Issue by CrazyGoku** [macrozheng/mall#9]
老哥 可以把app端源码po一下不？跪求

**Comment by macrozheng** [comment]
还在开发中

**Comment by JaonDong** [comment]
为啥不开源，一起开发

**Comment by yanglbme** [comment]
@macrozheng @JaonDong 我觉得开源出来，大家一起开发，会是一个很好的选择。凭借 GitHub 强大的社区，一定能把项目做得很棒，更受大家欢迎。

**Comment by wsh900221** [comment]
后台都开源了，我相信开发到一定程度时，前端自然也会开源的。大家还是耐心等待一下。

**Comment by xiazhenhua** [comment]
老哥，有没有做PC端的项目
